### ISSUE TITLE
add to npm - to make available in cordova registry

### ISSUE THREAD

**Issue by mobidev111** [Crypho/cordova-plugin-secure-storage#10]
See this fork: https://github.com/LikeMindNetworks/cordova-plugin-secure-storage/commit/7ffa92a67a06f4b85439d962f60f8d6f2aa5565f

**Comment by ggozad** [comment]
Was planning to do this anyway, would you mind doing a PR?

**Comment by ggozad** [comment]
@mobidev111 It's done in #12 . Waiting for the fork to remove from npm registry so we can release.

**Comment by ggozad** [comment]
Published.
