### ISSUE TITLE
Changing Passcodes (Android & iOS)

### ISSUE THREAD

**Issue by dcousens** [Crypho/cordova-plugin-secure-storage#106]
We know about ["Android Security: The Forgetful Keystore"](https://github.com/Crypho/cordova-plugin-secure-storage#android-keystore-deletion-on-security-setting-change),  but does the same apply to iOS for equivalent security?

My attention has been drawn to the following paragraph (page 14) from the [iOS security guide](https://www.apple.com/business/docs/iOS_Security_Guide.pdf):

> The class **kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly**
behaves the same as _kSecAttrAccessibleWhenUnlocked_, however it is only
available when the device is configured with a passcode.
> This class exists only in the system keybag; they don’t sync to iCloud Keychain, aren’t backed up, and aren’t included in escrow keybags. **If the passcode is removed or reset, the items are rendered useless by discarding the class keys.** 

Emphasis applied.

If we wanted to level the playing field for Android,  we could disable `setEncryptionRequired` by default,  and then enable it as an option for equivalent security to `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`.

Granted, this behaviour is only somewhat consistent since Android 6+ (ref: https://doridori.github.io/android-security-the-forgetful-keystore/).

**Comment by ggozad** [comment]
I would like to have a PR dealing with this across platforms. Bits of this are there for iOS.

**Comment by demetris-manikas** [comment]
Well I believe we should go the other way around. 
kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly should be used at all times.
This probably means dropping support for ios < 8.

**Comment by dcousens** [comment]
@demetris-manikas I think the balance lies in the middle.
Rather than allowing configuration of exactly which `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`,  I think the real question that exists is:

* Encrypt as `DeviceOnly`, or
* Encrypt as `WhenPasscodeSetThisDeviceOnly`

The two options are identical to `setEncryptionRequired` (on/off),  as all Android data is encrypted (by default) as `DeviceOnly` (AFAIK).

**Comment by ggozad** [comment]
Please keep options available for developers as a configuration setting for those who want to use it. Then sane defaults should provide an as secure as possible setup for all platforms.

**Comment by ggozad** [comment]
To be more clear on the above, leave options open as long as they are secure.
So the ios should require a passcode or touch id (as it does) and then the dev should be able to configure whether they want icloud backups.
