### ISSUE TITLE
Return storage safety information

### ISSUE THREAD

**Issue by dcousens** [Crypho/cordova-plugin-secure-storage#111]
Could the initialization inform the user of whether you're dealing with a "forgetful" key-store or not?
It would be helpful to streamline code/logic rather than dealing with platforms specifically in our own wrappers.

Especially seeing as `WhenPasscodeSetThisDeviceOnly` is forgetful too (wipes if passcode is changed).

**Comment by ggozad** [comment]
Nope, this is your responsibility.
