### ISSUE TITLE
v2.6.6 breaks it on windows platform!

### ISSUE THREAD

**Issue by digaus** [Crypho/cordova-plugin-secure-storage#113]
Works fine with v2.6.5 but with v2.6.6 windows platform throws 'Missing Command Error' when trying to create the secure storage...

**Comment by ggozad** [comment]
Nothing has changed afaik for windows in the last release. Could you please debug and figure it out, I don't have a windows machine available atm.

**Comment by digaus** [comment]
This breaks it: https://github.com/Crypho/cordova-plugin-secure-storage/commit/006e1ac35c15dc601616d328be558005b570f165#diff-58ee91177abb530230d402dc2de60904L79

The reason is that windows is reusing the iOS stuff:

```
// SecureStorage for Windows web interface and proxy parameters are the same as on iOS
// so we don't create own definition for Windows and simply re-use iOS
SecureStorageWindows = SecureStorageiOS;
```

**Comment by ggozad** [comment]
Ops yes you are right. Could you please override the constructor for windows so that it is as it used to be i.e. invoke success inside a setTimeout, run the tests on windows and make a PR?

**Comment by digaus** [comment]
Trying to add the tests as shown in the readme results in 'Error: Registry returned 404 for GET on https://registry.npmjs.org/myapp'
