### ISSUE TITLE
Support set/get multiple entries in one go

### ISSUE THREAD

**Issue by demetris-manikas** [Crypho/cordova-plugin-secure-storage#115]
I believe this would be a useful feature to add. Any thoughts?

**Comment by ggozad** [comment]
I would say no to this. Would rather keep things as minimal as possible and also the idea being that we do not want to encourage the use of securestorage as a generic storage this seems not of much use.

**Comment by demetris-manikas** [comment]
I was thinking it may speed up some apps by avoiding to use the bridge many times. Anyway...
