### ISSUE TITLE
"Error: nonce must have length from 7 to 13 octets" on KitKat when using `migrateLocalStorage: true`

### ISSUE THREAD

**Issue by jakub-g** [Crypho/cordova-plugin-secure-storage#117]
Hello,

I updated to 2.6.8 from an older version (2.2.x) and I've noticed the following issue;

- we construct SS instance with `migrateLocalStorage: true` flag (which is not publicly documented but I found out about it reading code and GH issues)
- when using `ss.set` we get an error `nonce must have length from 7 to 13 octets` on KitKat

Reading through the source code I think the issue is following:

1) init code calls a Java method which returns whether native AES is supported, this method is called back with `0` on KitKat:

```
SecureStorageAndroid = function (success, error, service, options) {
    var self = this;
    if (options) {
        this.options = _merge_options(this.options, options);
    }

    this.service = service;
    try {
        _executeNativeMethod(
            function (native_aes_supported) { <------ 0 on KitKat
```

then we have the code that updates the flag on the instance:

```
                checkMigrateToNativeAES = function () {
                    self.options.native = native_aes_supported && self.options.native;
```

BUT `checkMigrateToNativeAES` is never called if you have `{migrateLocalStorage: true}`:

```
                if (self.options.migrateLocalStorage){
                    self._migrate_to_native_storage(success);
                } else {
                    _executeNativeMethod(
                        function () {
                            checkMigrateToNativeAES();
                        },
                        function() {
                            self._migrate_to_native_storage(checkMigrateToNativeAES);
                        },
```

which means that the default value of `true` is kept in such case:

```
SecureStorageAndroid.prototype = {
    options: {
        native: true,
        migrateLocalStorage: false
    },
```

hence all subsequent calls to `get`/`set` see `native: true` and `native_get`/`_native_set` is called:

```
    get: function (success, error, key) {
        try {
            if (this.options.native) {
                this._native_get(success, error, key);
            } else {
                this._sjcl_get(success, error, key);
            }
        } catch (e) {
            error(e);
        }
    },
```

AFAIU `self.options.native = native_aes_supported && self.options.native` should be called directly in init callback, not inside `checkMigrateToNativeAES` function.

Without it, the behavior is backward incompatible: things stored on older version of the plugin with `_sjcl_set` are retrieved via `native_get` and `.get("KEY_STORED_ON_OLDER_VERSION")` fails. With the change I proposed, I could retrieve the value properly.

**Comment by jakub-g** [comment]
BTW can you explain why the KitKat has special treatment (perhaps pointing to some official documentation etc?) I could not find anything about it in Android documentation.

**Comment by demetris-manikas** [comment]
The option you used is undocumented because you should not use it. It is just there for testing purposes.

**Comment by jakub-g** [comment]
Hello @demetris-manikas thank you for your response.

Regarding what you wrote: since `migrateLocalStorage` is private and should not be used, then shouldn't `2.5.0` release have been a semver-major `3.0.0`? 

It was not a drop-in replacement for pre-2.5.0 version of the plugin: since older versions were storing things to localStorage, after upgrade of the plugin, the data stored on users' devices would no longer be reachable - hence it's a backward incompatible change.

If you don't want to make the option public, then feel free to discard my PR, but I think it might be valuable for some users to make it public. (I will do more testing on my side and let you know if find other issues.)

FYI what I'm working on to have context:

In our case, we are rewriting our app from Cordova to a native Android app, and seamlessly migrating some of the users' data is mandatory for good user experience; so I'm planning to first migrate data from localStorage to SharedPreferences in an intermediate release of Cordova app, and then reuse some pieces of the plugin's code in the new native app to import the data back.

**Comment by demetris-manikas** [comment]
@jakub-g I 'll try to explain you what is going on. The android implementation was underwent two major changes. One was to migrate storage from localeStorage to SharedPreferences and applies to all supported android versions KitKat (API 19) and above. The other one was to change the way that AES encryption occurs (from sjcl to native AES). The later can happen only for Lollipop and above and not for KitKat.
When installing the latest version entries will be moved to SharedPreferences from localStorage but the migration to native AES will happen only if the host is running Lollipop and above. If you wish to support KitKat you will certainly hit a wall because there is no java sjcl implementation AFAIK. You will have the entries in the SharedPreferences but no way to decipher them. Otherwise what you wish to do is probably doable.
Hope this helps

**Comment by ggozad** [comment]
Since there is no more feedback and this is an old issue, closing.
