### ISSUE TITLE
Unable to get, set-instead getting an error

### ISSUE THREAD

**Issue by chran8** [Crypho/cordova-plugin-secure-storage#119]
I am creating an Ionic application. This is my method I am executing...

```
saveDetails(){

  this.secureStorage.create('test')
  .then((storage: SecureStorageObject) => {
    setTimeout(() => {
    storage.set('DD', this.device.uuid)
       .then(
         setValue => { console.log("value has been set")},
         error => console.log("unable to set value")
     );
    }, 3000);

     storage.get('DD')
       .then(
         retrivedValue => {this.auth.create(retrivedValue)},
         error => console.error(error)
     );

  });
}
```

But when I go ahead and run this method, I get some type of error in xcode when running an emulator or on an actual device:

```
2017-07-03 17:36:40.834 MyApp[72027:4183169] Ionic Native: deviceready event fired after 745 ms
2017-07-03 17:36:43.003 MyApp[72027:4183169] ERROR: {"line":71,"column":45,"sourceURL":"file:///Users/user/Library/Developer/CoreSimulator/Devices/"some string"/data/Containers/Bundle/Application/"some string"/MyApp.app/www/plugins/cordova-plugin-secure-storage/www/securestorage.js","__zone_symbol__currentTask":{"type":"macroTask","state":"notScheduled","source":"setTimeout","zone":"<root>","cancelFn":null,"runCount":0}}
```
I've tried almost everything and can't seem to fix this

Thanks

**Comment by cmartin81** [comment]
I have the same problem. It works on android but not on IOS.

**Comment by cmartin81** [comment]
I fix it by running the code on a real device and by running it inside the platform.ready clause (this is for ionic, but there are a ready function for cordova also)

**Comment by demetris-manikas** [comment]
@chran8 To successfully get back a value you need to call get after the success callback. Try placing the call to get in the success callback of set.
Also bare in mind that when the error callback of get is called this means that the key is not present in the storage.

**Comment by chran8** [comment]
@demetris-manikas That is true, but the problem I have is that even if I have only 'set' in my method, I get the same error mentioned above. I get that error in Xcode regardless of using the set or get method

**Comment by demetris-manikas** [comment]
@chran8 Can you verify that the cordova deviceready event has fired before the calls to the plugin?

**Comment by chran8** [comment]
@demetris-manikas Yessir, I get the same error as mention above, even after nuking the project and starting a new one with the addition of the deviceready clause...
```
2017-07-03 17:36:40.834 MyApp[72027:4183169] Ionic Native: **deviceready** event fired after 821 ms
2017-07-03 17:36:43.003 MyApp[72027:4183169] ERROR: {"line":71,"column":45,"sourceURL":"file:///Users/user/Library/Developer/CoreSimulator/Devices/"some string"/data/Containers/Bundle/Application/"some string"/MyApp.app/www/plugins/cordova-plugin-secure-storage/www/securestorage.js","__zone_symbol__currentTask":{"type":"macroTask","state":"notScheduled","source":"setTimeout","zone":"<root>","cancelFn":null,"runCount":0}}
```
@cmartin81 Would you mind showing your implementation? Trying the same method but still getting the error even after nuking the project and starting a new one.

**Comment by cmartin81** [comment]
I made a provider that uses either localstorage if you are not on a device and the plugin if you are on a device:
`
class .....{

  async get(key) {
    if (this.platform.is('cordova')) {
      try {
        const storage: SecureStorageObject = await this.secureStorage.create(this.storageName);
        const result = await storage.get(key);
        return result
      } catch (e) {
        console.log('ERROR:', e);
        return null;
      }
    } else {
      return localStorage.getItem(key);
    }
  }

 set(key, value) {
    return new Promise((res, rej) => {
      if (this.platform.is('cordova')) {
        try {
          this.secureStorage.create(this.storageName)
            .then((storage: SecureStorageObject) => {
              return storage.set(key, value);
            })
            .then(() => {
              res();
            })
            .catch((error) => {
              console.log(error);
            })
        } catch (e) {
          console.log(e);
          return e;
        }
      } else {
        localStorage.setItem(key, value);
        res();
      }
    })
  }
`

And in my app.compontent.js
`export class MyApp {
  constructor(....) {
    this.initializeApp();
  }

  async start() {
   <Code to fetch item from storage>
  }

  initializeApp() {
    this.platform.ready()
      .then(this.start.bind(this))
      .then(() => {
      this.statusBar.styleDefault();
      this.splashScreen.hide();
    });
  }
}`

**Comment by cmartin81** [comment]
@chran8 Have you tried you code on an actual device? (It dosen't work on a simulator)

**Comment by chran8** [comment]
@cmartin81 Yes I've tried the code on an actual device and I get the same results

**Comment by demetris-manikas** [comment]
@chran8 I tried it on android and works as expected. @cmartin81  is right about checking whether the platform is cordova before making calls to native plugins.
Have you come up with anything?
