### ISSUE TITLE
Not Working on rooted android phones.

### ISSUE THREAD

**Issue by rishabh09** [Crypho/cordova-plugin-secure-storage#122]
On initializing the app i am getting error

> Error: Failed to load generated key pair from keystore

it is working fine on non-rooted phones

**Comment by demetris-manikas** [comment]
Hi! Sorry for the late reply.
No experience with rooted phones here. 
Could you supply some more information about the error?

**Comment by ggozad** [comment]
Rooted android is unfortunately not supported.
