### ISSUE TITLE
Empty string when getting long values

### ISSUE THREAD

**Issue by Cubaza** [Crypho/cordova-plugin-secure-storage#125]
Hi,
I have a problem with plugin. When im trying to put long string into storage it is returning empty string. For example when I try to put value like below:

> eyJhY2Nlc3NfdG9rZW4iOiJleUpoYkdjaU9pSklVelV4TWlKOS5leUpoZFdScGRDSTZJbnRjSW1Ob1lXNXVaV3hjSWpwY0lrVlRTVWRPWENJc1hDSnpaWE56YVc5dVNXUmNJanBjSWpaR05UaEZRemc1TUVGRlF6UkROVVJjSWl4Y0luSmxjWFZsYzNSSlpGd2lPakY5SWl3aWRIbHdaU0k2SWxWVFJWSWlMQ0oxYzJWeUlqb2llMXdpWkdWMmFXTmxTV1JjSWpvek9TeGNJblZ6WlhKSlpGd2lPbHdpVFVzeFhDSXNYQ0oxYzJWeVUyVnpjMmx2Ymtsa1hDSTZNakkyZlNJc0ltRjFkR2h2Y21sMGFXVnpJanBiSWxKUFRFVmZWVk5GVWlKZExDSmxlSEFpT2pFMU1EUXdNREV6TWpOOS5Iekd5YUl0SVM0YVkzeHdKVXA0Q2RnM2NkTVZDQ0JsVGpJN1pwU29na0RpUU5RT2hvTWlSRUl1azBTWUYzdUI3NG1jaE40Q0RPNHlyeU9SSGlkUlhBQSIsInRva2VuX3R5cGUiOiJCZWFyZXIiLCJleHBpcmVzX2luIjoiMzYwMCIsInJlZnJlc2hfdG9rZW4iOiJleUpoYkdjaU9pSklVelV4TWlKOS5leUp5WldaeVpYTm9YM1J2YTJWdUlqb2lWQ0lzSW1GMVpHbDBJam9pZTF3aVkyaGhibTVsYkZ3aU9sd2lSVk5KUjA1Y0lpeGNJbk5sYzNOcGIyNUpaRndpT2x3aU5rWTFPRVZET0Rrd1FVVkRORU0xUkZ3aUxGd2ljbVZ4ZFdWemRFbGtYQ0k2TVgwaUxDSjBlWEJsSWpvaVZWTkZVaUlzSW5WelpYSWlPaUo3WENKa1pYWnBZMlZKWkZ3aU9qTTVMRndpZFhObGNrbGtYQ0k2WENKTlN6RmNJaXhjSW5WelpYSlRaWE56YVc5dVNXUmNJam95TWpaOUlpd2lZWFYwYUc5eWFYUnBaWE1pT2xzaVVrOU1SVjlWVTBWU0lsMHNJbVY0Y0NJNk1UVXdOalU0T1RjeU0zMC5aaDRjRzRtRTQ1dU1FYVp6VGlUcmFObHFmWGtCend3aENXeGQyWEEtWXBkQy1hVFVYMnl3ODQ2TDlLb3R2LUJCNE1QX3hpQjE4Rk5qUWJ6cDcyYi1YdyIsIm1lc3NhZ2UiOm51bGwsImF1dGhVc2VyIjp7InVzZXJJZCI6Ik1LMSIsInJvbGVzIjpbIlJPTEVfVVNFUiJdfSwiZGV2aWNlSWQiOjM5LCJyZXN1bHRDb2RlIjoiT0siLCJfbGlua3MiOnt9LCJzZWxlY3RlZFN5c3RlbSI6eyJpZCI6MTAwLCJ1bml0Q29kZSI6ImNvZGUiLCJ1bml0TmFtZSI6IkJTIEtyYWvzdyIsInVuaXREZXNjcmlwdGlvbiI6IkJhbmtvd29zYyBrb3Jwb3JhY3lqbmEiLCJ1bmlxdWVEZXZpY2VJZCI6ImY1M2E3YTA3LWQ5NWMtNDVlMi05MWU1LTJhZWRhNDlkMmY2YSIsImhhc2hlZFN5c3RlbUlkIjoiWmpVellUZGhNRGN0WkRrMVl5MDBOV1V5TFRreFpUVXRNbUZsWkdFME9XUXlaalpoIn19

It is ok because i've got success response from my code. But when I want to read it with storage.get('key') it is returnig empty string = "". Is there any maximum lenght of value which i can put into the storage or I'm doing wrong  approach? I'll be very glad to get some advice or response.

**Comment by demetris-manikas** [comment]
Hi, I am on vacation until the end of the week. 
Does this happen on all platforms? 
It would be great if you prepared a PR with a failing test.

**Comment by Cubaza** [comment]
I found what i was doing wrong. I save to one plugin and read from another(i was testing two separate plugins). On your plugin it is working ok. Sorry that I interrupted you on vacation.
