### ISSUE TITLE
Differ between "device not secure" and other exceptions on initialization

### ISSUE THREAD

**Issue by Writech** [Crypho/cordova-plugin-secure-storage#126]
The issue is that I dont know of a way to differ between "device just not having sufficient screen lock set up exception" and possibly some other exceptions occurring during SecureStorage initialization. The example in the Readme regarding checking for device being secure leaves an impression that ONLY time that an exception occurrs during initialization is when the device does not have sufficient screen lock set up. But I guess this is not the case, definitely there is a possibility of some other exceptions occurring internal to the library. 

```javascript
let secureStorageAvailable = false;
let deviceSecure = false;

const successCallback = function () {
    secureStorageAvailable = true;
    console.log('OK');
};

const errorCallback = function (err) {
if(err.name = 'Some specific error name describing device not having a screen lock'){
    secureStorageAvailable = false;
    device
} else {
    secureStorageAvailable = false;
    console.error(err);
}
};

const storeName = 'my_app';

const ss = new cordova.plugins.SecureStorage(successCallback, errorCallback, storeName);
```

I would like to know specifically when initialization raises an error because of device not having a screen lock set up. This way I could invoke the `secureDevice()` method, show a message describing the problem to the user and bring in the device screen lock settings page. If any other exception occurs I want to simply disable the SecureStorage functionality in my app entirely.

**Does the error being thrown for device not being secure have a specific name to check against?**

I'm thinking of doing something in lines of:

```javascript
let secureStorageAvailable = false;
let deviceSecure = false;
let ss = null;

const successCallback = function () {
    secureStorageAvailable = true;
    deviceSecure = true;
    console.log('Device secure. Continue saving client\'s data.');
    // ...
};

const errorCallback = function (err) {
    if (err.name = 'Some specific error name describing device not having a screen lock') {
        secureStorageAvailable = true;
        ss.secureDevice(() => {
                deviceSecure = true;
                console.log('Device secure. Continue saving client\'s data.');
                // ...
        }, () => {
                deviceSecure = false;
                console.log('Device still not secure. Retry initialization or cancel.');
                // ...
        });
    } else {
        secureStorageAvailable = false;
        deviceSecure = false;
        console.error(err);
        // Some other exception occurred. Retry initialization or cancel.
    }
};

const storeName = 'my_app';

ss = new cordova.plugins.SecureStorage(successCallback, errorCallback, storeName);
```

**Comment by demetris-manikas** [comment]
When initialization fails due to device not being secured the errorCallback is called with the string "Device is not secure" as a parameter.
