### ISSUE TITLE
Android Kitkat get JSON error

### ISSUE THREAD

**Issue by rjakl** [Crypho/cordova-plugin-secure-storage#127]
Hello, when I want to receive my stored data, I get "Error: JSON error" on Android Kitkat 4.4.2. When I set data, there's no error. Other Android versions are working fine. I've got pattern screen lock.
```
storage.get(
    function (value) {
        callback(value);
    },
    function (error) {  // <== here ===
        alert( error);
        callback(null);
    },
    'myData'
);
```
![error_jpg](https://user-images.githubusercontent.com/25985635/30064132-20087b12-9251-11e7-91cf-cead4e44bb19.jpg)

**UPDATE**
(Android emulator) I changed my lock to PIN and some alert window asked me for credential storage password. So I entered my PIN, toast show "credential storage is enabled", confirmed with my PIN, but I still get the same "JSON error".

![pw_credential](https://user-images.githubusercontent.com/25985635/30126597-a8cb5334-933c-11e7-9eae-c055f687976f.jpg)

**Comment by ggozad** [comment]
Could you please run the tests and report any errors?

**Comment by rjakl** [comment]
All tests passed. I noticed that in tests there is get function called inside secure storage init success handler, not after initialization. So I moved get function there too and now It's working fine. Thanks. :)
