### ISSUE TITLE
cordova.plugins.SecureStorage is not a function??

### ISSUE THREAD

**Issue by clarklight** [Crypho/cordova-plugin-secure-storage#13]
Hi 

  I just installed the plugin, and have an error cordova.plugins.SecureStorage is not a function, not sure why is this happening. 

     var ss = new SecureStorage(
    function () { alert('Success')},
    function (error) { alert('Error ' + error); },
    'my_app');

**Comment by ggozad** [comment]
Can you give me a few more details? iOS, Android? Versions?

**Comment by ggozad** [comment]
Also it's actually cordova.plugins.SecureStorage not SecureStorage. Is this it?

**Comment by clarklight** [comment]
Hi Sorry yes, Android running on 5.0. Yer i tried var ss = new cordova.plugins.SecureStorage(

And it called that error so i tried    var ss = new SecureStorage(
But it also called the same error.

**Comment by ggozad** [comment]
Could you please try with an empty app and describe the steps you follow?
I made a new app, run
cordova plugin add cordova-plugin-secure-storage
and can see the constructor fine.

**Comment by clarklight** [comment]
Hi I just tried it again, i created a brandnew app. The only thing i have in the html page is  the div and a script below. 

       <script>
     
          document.addEventListener("deviceready", function(){ 
   var ss = new cordova.plugins.SecureStorage(
    function () { console.log('Success')},
    function (error) { console.log('Error ' + error); },
    'my_app');
 })
     
    </script>


I first tried to use the phonegap plugin version of the crypho, it didnt work, so i forked a version from github to build the plugin to test. It installed but it has that isnt a function error. 

There is nothing else in the app.

**Comment by clarklight** [comment]
Ahhh managed to make some progress now it is calling. 

cordova-plugin-secure-storage.sjcl_ss not found

And a few error in the log 

deviceready has not fired after 5 seconds.
cordova.js:1179 Channel not fired: onCordovaReady
cordova.js:1179 Channel not fired: onFileSystemPathsReady
cordova.js:1179 Channel not fired: onCordovaConnectionReady
cordova.js:1179 Channel not fired: onCordovaInfoReady

**Comment by clarklight** [comment]
Hiii 

   I think i might have got it working, but it asked me to set my screen lock?? And i have to have a screen lock on for it to work??

**Comment by ggozad** [comment]
Could you please let us know what was the problem?
You do indeed need to have screen lock to access certain parts of the crypto API.

**Comment by clarklight** [comment]
Hi thanks, the first problem was my mistake i was pulling from a wrong fork.

 But when i fixed that up, the second problem was with the id,because i am using phonegap build. The reference had to be changed. So i just renamed the id to com.secure.plugins.crypho, but because the securestorage.js is referencing the sjcl_ss, so i also had to change the first line of the sjcl_ss to var sjcl_ss = cordova.require('com.secure.plugins.crypho.sjcl_ss'); So it is referencing it correctly. 

Then it worked. 

So a quick question, if i just want to put some encrypted data into secure storage for Android/IOS, would i also need the screen lock to be on?? the ss.set/ss.get for example?

**Comment by ggozad** [comment]
You shouldn't have to do any of that. Would you please try again by:
```
cordova create test
cd test
cordova plugin add cordova-plugin-secure-storage
cordova platform add android
```
Then try using the storage.
To your second question:
Yes, in order to use the RSA storage built in with android, you need to have some sort of locking on the phone. The minimum is a PIN password.

**Comment by mysoko** [comment]
I also encountered the same problem：『TypeError: Cannot read property 'SecureStorage' of undefined  
』

Js files are loaded in.

![1](https://cloud.githubusercontent.com/assets/75619/11417956/54d61bf6-9456-11e5-9776-b42bac64c967.png)

code：
```js
return new cordova.plugins.SecureStorage(
                    function () { console.log('Success') },
                    function (error) { console.error('Error ' + error); },
                    name);
```

**Comment by ggozad** [comment]
Perhaps you guys could help debug this? I am not seeing this in a clean installation. Is this android also?
Could you try to debug and figure out what happens?

**Comment by clarklight** [comment]
Hey guys 

    I had that problem before but i have resolved that. @mysoko did you install it thru cordova or Phonegap? 
I had that problem when i packaged it and installed through phonegap, the core reason for me was the file directory name. I just renamed the file; as it was calling SecureStorage of undefined, it isn't seeing that file i assumed. 

Have a look if that solve your problem.

**Comment by ggozad** [comment]
@clarklight can you please elaborate a bit? What file directory?

**Comment by ggozad** [comment]
Also @mysoko are you also on phonegap? We've only tested with crodova, perhaps there are some quirks we need to figure out on phonegap.

**Comment by mysoko** [comment]
crodova 5.4.1, cordova android 5.0.0

**Comment by mysoko** [comment]
Probably locate the problem, load order problem js of, cordova js plugin loader is asynchronous, so not every get cordova.plugins.SecureStorage

![2](https://cloud.githubusercontent.com/assets/75619/11418283/7842971a-9459-11e5-86e1-bdd8884e36ff.png)

![3](https://cloud.githubusercontent.com/assets/75619/11418286/7dc12d3c-9459-11e5-9c01-dc9a31b8e02f.png)

**Comment by demetris-manikas** [comment]
From the trace looks like you try to instantiate the SecureStorage before having received the deviceready event,

Just tested on Cordova 5.4.1 fresh project (android, browser platforms) the following code and did not experience any exceptions
```javascript
var app = {
    // Application Constructor
    initialize: function() {
        this.bindEvents();
    },
    // Bind Event Listeners
    //
    // Bind any events that are required on startup. Common events are:
    // 'load', 'deviceready', 'offline', and 'online'.
    bindEvents: function() {
        document.addEventListener('deviceready', this.onDeviceReady, false);
    },
    // deviceready Event Handler
    //
    // The scope of 'this' is the event. In order to call the 'receivedEvent'
    // function, we must explicitly call 'app.receivedEvent(...);'
    onDeviceReady: function() {
        app.receivedEvent('deviceready');
        var ss = new cordova.plugins.SecureStorage(
                    function () { console.log('Success') },
                    function (error) { console.error('Error ' + error); },
                    name);

    },
    // Update DOM on a Received Event
    receivedEvent: function(id) {
        var parentElement = document.getElementById(id);
        var listeningElement = parentElement.querySelector('.listening');
        var receivedElement = parentElement.querySelector('.received');

        listeningElement.setAttribute('style', 'display:none;');
        receivedElement.setAttribute('style', 'display:block;');

        console.log('Received Event: ' + id);
    }
};

app.initialize();
```

**Comment by demetris-manikas** [comment]
@mysoko  Also note that at least on Android the plugin is usable only after the success method has been called

**Comment by ggozad** [comment]
@mysoko @clarklight can you confirm what @demetris-manikas suggests solves your problem?

**Comment by mysoko** [comment]
@demetris-manikas @ggozad 

Loading problem, put onDeviceReady's ok.
Because the angular and ui-router route I use, will first perform homeCtrl so it did not get any information.

We made the following changes:

```js
angular.config(['$stateProvider', '$urlRouterProvider', function ($stateProvider, $urlRouterProvider) {
        //$urlRouterProvider.otherwise("/");
```
to：
```js
 onDeviceReady: function() {
        location.hash = '/';
    }
```

First contact cordova encountered many problems, thank you for help.

**Comment by ggozad** [comment]
Closing this, @clarklight if it still persists, let me know and I will open it. Added an FAQ section on the README with explicit instructions.
