### ISSUE TITLE
question on usage

### ISSUE THREAD

**Issue by jamesdixon** [Crypho/cordova-plugin-secure-storage#130]
Hi,

I found it slightly odd that an error is thrown if a key cannot be found in the keychain. Is that intended? I feel like if no key is found, no value would be returned.

Is this the intended usage?

Thanks!

**Comment by ggozad** [comment]
Hey James,
This was intended when first implemented in order to allow say nulls to be stored as values.
I will agree that it should have not been the case, but it's a bit late for breaking API changes.
So, sorry, but this is unlikely to change.

**Comment by jamesdixon** [comment]
@ggozad no worries at all! Thank you for the quick reply! Cheers.
