### ISSUE TITLE
Uncaught (in promise): cordova_not_available

### ISSUE THREAD

**Issue by gigocabrera** [Crypho/cordova-plugin-secure-storage#131]
I'm trying to add Secure Storage plugin to my ionic app following the instructions below:
http://ionicframework.com/docs/native/secure-storage/

I added the plugin to my app's module to the provider section and added the code below to my app.component.ts inside `platform.ready()`

```
// Secure Storage
this.secureStorage = new SecureStorage();
this.secureStorage.create('myappstorage')
   .then((storage: SecureStorageObject) => {
        // Language
        storage.get('language')
          .then(data => {
            console.log('language', data);
            translateService.use(data);
            this.translateProvider.use(data);
          }
      );        
});
```

However, I'm getting the following error:

```
core.es5.js:1020 ERROR Error: Uncaught (in promise): cordova_not_available
    at c (polyfills.js:3)
    at c (polyfills.js:3)
    at polyfills.js:3
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (core.es5.js:3881)
    at t.invokeTask (polyfills.js:3)
    at r.runTask (polyfills.js:3)
    at o (polyfills.js:3)
    at HTMLDocument.invoke (polyfills.js:3)
```

I'm using the latest ionic as of today.

Any ideas?

**Comment by gigocabrera** [comment]
Do I need to wrap it like this to evaluate for plarform? Maybe?

```
if (platform.is('cordova')) {
    ... [secure storage code here]
}
```

**Comment by ggozad** [comment]
This looks very much like an issue with ionic's wrapper over our plugin.
While it's great that ionic decided to use our plugin as their goto secure storage, we do not have the resources to test on ionic and support ionic's wrapper. You might have more luck asking over at their repos.
I am gonna leave this open for a while in case people who use ionic want to chime in.

**Comment by gigocabrera** [comment]
Thank you @ggozad, I'll reach out to them

**Comment by demetris-manikas** [comment]
@gigocabrera Hi. I believe you have to test platform.is("cordova").

**Comment by gigocabrera** [comment]
I found this
https://stackoverflow.com/questions/42840951/uncaught-in-promise-cordova-not-available-in-ionic-2

**Comment by gigocabrera** [comment]
@demetris-manikas thank you!!!
