### ISSUE TITLE
There is no Browser Support 

### ISSUE THREAD

**Issue by Vishwa17** [Crypho/cordova-plugin-secure-storage#137]
In Ionic website it is mentioned , there is browser support but it doesn't seems there is browser code  ?
Could you please help me on this?

**Comment by ggozad** [comment]
The browser support is only supposed to be used for testing. Not production.

**Comment by Vishwa17** [comment]
SO which storage i can use for IONIC Progressive Web Apps ?

**Comment by BorntraegerMarc** [comment]
@Vishwa17 Check out https://stackoverflow.com/questions/22811160/store-data-locally-using-html-and-javascript for example
