### ISSUE TITLE
Can't resolve all parameters for SecureStorageObject: (?).

### ISSUE THREAD

**Issue by ElRochito** [Crypho/cordova-plugin-secure-storage#139]
Hi,

I've got this message when I run my app on android device "Can't resolve all parameters for SecureStorageObject: (?)."

Has someone already had this problem ?

I'm wondering if this is not an import problem in the app.module.ts file but I do not see which one.

Thanks

**Comment by WillianAS** [comment]
I have same problem!
Did you solve this problem?

**Comment by WillianAS** [comment]
Me too! 
But I remove the SecureStorageObject of the provider. Now I have a problem with "npm err elifecycle" hahahahaha
Thanks for reply!
