### ISSUE TITLE
No callback is being called

### ISSUE THREAD

**Issue by Cakaaa** [Crypho/cordova-plugin-secure-storage#141]
Hey guys,

I have successfully installed the plugin, at least I think, but none of the callbacks are being called so I am not sure if its working.

The code that i am executing after the 'deviceready' event:

`
        let keyChainId = 'testbucket';

        let key = 'password';
        let value = 'mySecretttt';

        let ss = new window.cordova.plugins.SecureStorage(
            () => {
                // not called...
                alert('Success');
            },
            (error) => {
                // not called...
                alert('Error ' + error);
            }, keyChainId);

        if (ss !== undefined && ss !== null) {
            // this one gets called
            alert("initialised Secure Storage. Waiting for callback...");
        }

`

The alerts from the callbacks arent called at all but the alert in the undefined and null check does get called so it seems the object is created.

**Comment by dganzella** [comment]
for me its working
download zip of the project
use cordova plugin add <path_to_plugin> --nofetch
add a button to html
when button is pressed, call these

            var ss = new cordova.plugins.SecureStorage(
                function () {
                    console.log('Success STORAGE');
                     ss.keys(
                        function (keys) {
                            console.log(keys);
                        },
                        function (error) { console.log('Error STORAGE 2: ' + error); });
                },
                function (error) { console.log('Error STORAGE ' + error); },
                'com.pizza1.pizza2');

add com.pizza1.pizza2 to your keychain sharing on capabilities

**Comment by DennisSmolek** [comment]
@Cakaaa will you close the issue if you got it working and it was more related to your code?
