### ISSUE TITLE
Take Over Maintenance

### ISSUE THREAD

**Issue by MaKleSoft** [Crypho/cordova-plugin-secure-storage#143]
Sent an email to dev@crypho.com but didn't get an answer, so I'm trying to get in touch this way. I'm interested in taking over maintenance for this plugin as part of the [Padlock](https://github.com/maklesoft/padlock/) project. Let me know what you think! /cc @ggozad @demetris-manikas

**Comment by ggozad** [comment]
Hey there, this is my bad, I have been stumped with work and your message got lost into oblivion.
I will talk with Demetris and if ok get back to you next week?

**Comment by padlock** [comment]
Yep, sounds good!

**Comment by MaKleSoft** [comment]
Yep, sounds good!

**Comment by BorntraegerMarc** [comment]
I would love to see a new maintainer!!!
