### ISSUE TITLE
Is it possible to invoke  secretkey from android keystore file.

### ISSUE THREAD

**Issue by muttineni2020** [Crypho/cordova-plugin-secure-storage#144]
For security concern, would it be possible to invoke secret key alias stored in androidkeystore ( while signing the apk).  Can anybody help me on this issue.

Thanks,

**Comment by ggozad** [comment]
I am sorry I have no idea what you are talking about. Could you please phrase this a bit better?

**Comment by ggozad** [comment]
Oh I see. No I am afraid this plugin is meant to encrypt and store user secrets.

**Comment by muttineni2020** [comment]
Any other solution or suggestion you might have. We are having hard time to get this kind functionality.

**Comment by ggozad** [comment]
I am afraid not. Gonna reopen this for a week or so in case someone else does.
To be honest, I can't think of why you would want to do what you want to do. Relying on a secret that is not user known but rather client known feels wrong, so perhaps you want to explain a bit further.
