### ISSUE TITLE
When does the "Android Security: The Forgetful Keystore" present it self?

### ISSUE THREAD

**Issue by distante** [Crypho/cordova-plugin-secure-storage#145]
I am try to figure out how to control this problem but does not matter what I do (change from no screen-lock, to pin,password, path, etc) this problem does not happens.

I have tried on Devices with Android 5.0.1, 6 and 8, also on Emulator with Android 5 and 7. Is this still a problem?

**Comment by ggozad** [comment]
Please, this is not reddit.

**Comment by distante** [comment]
Yes but this plug [documentation ](https://github.com/Crypho/cordova-plugin-secure-storage#android-keystore-deletion-on-security-setting-change ) says :

> Android keystore deletion on security setting change
> Changing the lock screen type on Android erases the keystore (issues 61989 and 210402). This is also described in the Android Security: The Forgetful Keystore blog post.
> 
> This means that any values saved using the plugin could be lost if the user changes security settings. The plugin should therefore be used as a secure credential cache and not persistent storage on Android.

And yet I am unable to reproduce this on devices or emulators. Do I have to go to reddit and there about this plugin?
