### ISSUE TITLE
Google Smart Lock

### ISSUE THREAD

**Issue by newlegendmedia** [Crypho/cordova-plugin-secure-storage#146]
We have implemented this plugin and its working great! 

However, we came across Google Smartlock and it has some features that would help our users, such as sync of credentials between websites and apps. 

Do you plan to implement Google Smartlocks in this plugin?  I currently dont see any Cordova plugins that implement it.

**Comment by demetris-manikas** [comment]
Hi Jeff. Password management is not within the purposes of this plugin. So I don't think it will be implemented. 
Thanks.

**Comment by gnarco** [comment]
Yes, but using smart lock like icloud for backuping secured secret ?
