### ISSUE TITLE
Can android phone configuration (off) the system password settings？

### ISSUE THREAD

**Issue by mysoko** [Crypho/cordova-plugin-secure-storage#15]
Most mobile phone users (especially android user) will not set the system password。

If you do not set up simply impossible, I do not want to force the user to set up:

![image](https://cloud.githubusercontent.com/assets/75619/11420060/8a21d092-9466-11e5-9f94-9d4bc1601956.png)

**Comment by ggozad** [comment]
No, it is not possible. Having at least a PIN password is a requirement from the OS to get access to certain crypto APIs.
