### ISSUE TITLE
Ionic 3

### ISSUE THREAD

**Issue by craidencool13** [Crypho/cordova-plugin-secure-storage#150]
Hi, I am currently using Ionic 3 framework and I would just like to ask how do you completely wipe the storage data upon uninstallation of the app. Thanks!

**Comment by demetris-manikas** [comment]
To avoid automated backup/restore 

IOS: set the KeychainAccessibility to a *ThisDeviceOnly setting.

Android: change the manifest file to read as follows
<manifest ... >
    ...
    <application android:allowBackup="false" ... >
        ...
    </application>
</manifest>
See https://developer.android.com/guide/topics/data/autobackup#EnablingAutoBackup

@ggozad Should this be added to the README?

**Comment by craidencool13** [comment]
Thank you for responding @demetris-manikas !
