### ISSUE TITLE
Can multiple Android apps from a Company access the same shared data?

### ISSUE THREAD

**Issue by ajayambre** [Crypho/cordova-plugin-secure-storage#151]
I apologize for posting a question here, but I could not find a detailed documentation explaining how multiple apps from the same Company can use this plugin to share data between them.

We were able to make this work on iOS by using the same string value in the KeyChain preferences settings in XCode and when creating the SecureStorage in our code. But could not find something similar for our Android app.

Use Case:
We have multiple Enterprise apps built using Ionic 3 and all of them connect to the same server.
The device needs to be authorized using a code before the users are allowed to login.
The code is generated by an administrator on the server and shared with the user via an email.

We are trying to avoid a situation where the Admin needs to generate a separate code for each app that the user installs on his device.

When the app starts it looks for a key in the SecureStorage and if present uses that as the device ID.
If the key is not present in the SecureStorage, we get the uuid using the Device plugin and store it using the SecureStorage plugin.

We were able to make this work on iOS as the apps were able to access the shared data from the KeyChain.

On Android, the apps are not getting the key from the SecureStorage and so each app tries to generate using the Device plugin. Starting Android 8, the Device plugin returns a different value for each app even if it is published by the same Company.

Apologies again for posting a question here.
Any help/guidance on this would be greatly appreciated
Thanks!

**Comment by demetris-manikas** [comment]
Hi @ajayambre 
Not sure if this is going to work but check

https://developer.android.com/reference/android/content/Context.html#MODE_PRIVATE  and
https://stackoverflow.com/questions/6354035/two-android-applications-with-the-same-user-id

Beware that the SharedPreferences instance is generated using 
getContext().getPackageName() + "." + service. 

Please report back if you manage to make it work.

**Comment by ajayambre** [comment]
Thank you @demetris-manikas 

I added the same value for `android:sharedUserId` in `AndroidManifest.xml` for both my apps. But it was not enough.

I was able to make this work but had to do the below code changes.

Change 1: 
As you rightly said, the SharedPreferences instance had to be generated in a different way as every app will have a unique package name. I changed this and stripped the last part of the package name. 
So now apps from `com.mycompany.app1` and `com.mycompany.app2` will be able to access each others SharedPreferences but app with `com.othercompany.app` will not be able to access it.

`private String service2alias(String service) {`
&nbsp;&nbsp;&nbsp;&nbsp;`        String packageName = getContext().getPackageName();`
&nbsp;&nbsp;&nbsp;&nbsp;`        packageName = packageName.substring(0, packageName.lastIndexOf("."));`
&nbsp;&nbsp;&nbsp;&nbsp;`        String res = packageName + "." + service;`
&nbsp;&nbsp;&nbsp;&nbsp;`        return  res;`
`    }`

Change 2:
As mentioned [in this Stackoverflow link](https://stackoverflow.com/questions/6030321/android-retrieving-shared-preferences-of-other-application),  an app can read other apps SharedPreferences by using [createPackageContext](https://developer.android.com/reference/android/content/Context.html#createPackageContext(java.lang.String,%20int)). So I added another parameter `packageName` to the `init` action and used the `createPackageContext` method to create the Context and passed that to the `SharedPreferencesHandler ` constructor.

`context.createPackageContext(packageName, Context.CONTEXT_IGNORE_SECURITY | Context.CONTEXT_INCLUDE_CODE);`

Result:
I used the same `packageName` parameter `com.example.app1` for creating the SecureStorage from both my apps.
App1 inserted a value in the SecureStorage.
App2 was able to read that value from the SecureStorage.

I tested by changing the `android:sharedUserId` to a different value in my App2 and then it could not read the value stored by App1. 

The additional parameter is required specifically for Android and can be ignored for iOS and Windows.
Please let me know what you think of this solution.


Thank you for this plugin. I would love to contibute to it! :)

**Comment by demetris-manikas** [comment]
I would love to see a PR on this.
Lets see some code!

**Comment by ggozad** [comment]
This looks to me as a bad idea. How do you handle the shared secret in this case?

**Comment by ajayambre** [comment]
Hi @ggozad 

I am not sure if I understand your concern correctly.

Is it because of the flags `Context.CONTEXT_IGNORE_SECURITY | Context.CONTEXT_INCLUDE_CODE` OR with the idea of using the `createPackageContext` altogether.

If it is just because of the flags, then I tried doing `context.createPackageContext(packageName, 0)` and that still works if both the applications use the same `android:sharedUserId`.

**Comment by demetris-manikas** [comment]
@ggozad They are called SharedPreferences if you noticed...
@ajayambre My experience with ggozad is that when he sets his mind about something it is hard if not impossible to change it. So I recommend you fork this project and realize your idea. Sorry for letting you think you would contribute here.

**Comment by ggozad** [comment]
Hey @ajayambre,
The flags are indeed the problem. They would potentially allow other apps to also read the preferences and compromise the key. When passing `0` instead of `Context.CONTEXT_IGNORE_SECURITY | Context.CONTEXT_INCLUDE_CODE` you are essentially passing all the flags together, it's a bit mask, see https://www.learncpp.com/cpp-tutorial/3-8a-bit-flags-and-bit-masks/ for example.

**Comment by ajayambre** [comment]
Thanks for the detailed explanation @ggozad 
Sorry for the delayed response.

Request you to please have a look at the below code.

Consider App1 with `com.example.app1` as package name.
It uses `com.example.app1` as packageName param when creating the SecureStorage. 
The SharedPreferencesHandler would be created with the same default Context as it is being done with the current implementation as `context.getPackageName().equals(packageName)` is `true`.

Consider another App2 with `com.example.app2` as package name.
It uses `com.example.app1` as packageName param when creating the SecureStorage. 
It is able to gain access and read the data from the SecureStorage created by App1.

Does this mean we have a potential security problem with the current implementation?

`SharedPreferencesHandler PREFS = new SharedPreferencesHandler(alias + "_SS",`  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`getPackageContext(getContext(), packageName));`

`private Context getPackageContext(Context context, String packageName) {`
&nbsp;&nbsp;&nbsp;&nbsp;`        Context pkgContext = null;`
&nbsp;&nbsp;&nbsp;&nbsp;`        if (context.getPackageName().equals(packageName)) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            pkgContext = context;`
&nbsp;&nbsp;&nbsp;&nbsp;`        } else {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            try {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`                pkgContext = context.createPackageContext(packageName, 0);`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            } catch (Exception e) {`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`                e.printStackTrace();`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`                pkgContext = context;`
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;`            }`
&nbsp;&nbsp;&nbsp;&nbsp; `       }`
&nbsp;&nbsp;&nbsp;&nbsp; `       return pkgContext;`
 `   }`

**Comment by ggozad** [comment]
Hey, I had a closer look at this. As long as you pass `0` to `createPackageContext` you should be fine, you are merely passing a different package name to create your package context.
So it should be ok to share the storage across apps this way.

**Comment by ajayambre** [comment]
Thank you @ggozad 
Can I submit a PR for this?

**Comment by ggozad** [comment]
@ajayambre Feel free to do so. It should not be a default behavior, perhaps a config option is appropriate.

**Comment by ggozad** [comment]
@ajayambre gonna close this as there is no issue to resolve. Waiting for your PR.

**Comment by ajayambre** [comment]
@ggozad  As suggested, have added an optional packageName option for Android.
There are no breaking changes for existing apps and I expect that they will be able to fetch values for previously saved keys.
