### ISSUE TITLE
Where can I inspect the saved passwords on my iOS device?

### ISSUE THREAD

**Issue by FarhadG** [Crypho/cordova-plugin-secure-storage#156]
I understand that all data is being stored within iOS Keychain, however, as I'm developing and running the application on my iPhone, I don't see the actual values stored in the keychain. I'm able to set and retrieve the data, however, when I go to `Settings`>`Passwords & Accounts`>`Website & App Passwords`, I don't see the data there. I'm assuming I'm looking in the wrong place?

**Comment by ggozad** [comment]
There isn't really a place where you can see the key/values. They won't be shown under Website & App Passwords. IIRC this is possible if you set up "Shared web credentials" but your mileage may vary.

**Comment by FarhadG** [comment]
Thanks for the quick response, @ggozad! I guess I'm curious on how to ensure others don't have access to these credentials. If I understand correctly, the only thing that distinguishes the secure storage access is the provided `key` to define its domain space. Given this `key` is set within the Cordova app (i.e. frontend), I'd imagine it would be pretty easy for anyone else to get access to this key and retrieve data from the local hardware?

Thank you, in advance, for your help!

**Comment by FarhadG** [comment]
Ah, I see! Thanks for that clarification, @ggozad . So, by `key`/`value` of the domain space, the following would be represented, more-or-less, by the following underlying dictionary:

```
var ss = new cordova.plugins.SecureStorage(console.log, console.error, 'my_app');
ss.set(console.log,console.error, 'mykey', 'myvalue');

/*


{
  'my_app': {
    'myKey': 'myValue'
  }
}


*/
```
