### ISSUE TITLE
Dependency on SAMKeychain

### ISSUE THREAD

**Issue by danicholls** [Crypho/cordova-plugin-secure-storage#160]
I don't see any issues here about it, which is a good sign, but over on the [SAMKeychain repo](https://github.com/soffes/SAMKeychain/issues) it looks like some folks are having trouble with iOS12.

Since the maintainer is not replying, it's hard for me to know if this is a real problem or people misusing things. Any need/desire to switch dependencies?

Thanks!

**Comment by demetris-manikas** [comment]
Hi.
@jimmymultani Could you please file a separate issue describing the problems you face on android?

**Comment by JimmyMultani** [comment]
Hey @demetris-manikas, I tracked down the issue to be on my end, and not that of the plugin. I'm going to delete my previous comment so it doesn't pollute this issue with irrelevant statements.

Sorry for the confusion.

**Comment by demetris-manikas** [comment]
@danicholls Since nobody has filed any issues on problems with iOS I 'll close this for now.
If you have any suggestions on switching dependency on SAMKeychain we 'll be happy to listen to it.
Thanks for your interest.
