### ISSUE TITLE
uncaught exception error

### ISSUE THREAD

**Issue by jhoogeboom** [Crypho/cordova-plugin-secure-storage#161]
Using this with ionic 4, and it's [wrapper around this plugin](https://ionicframework.com/docs/native/secure-storage)

I'm just running the example provided, making a store, getting and setting keys but running into an uncaught exception when removing a key.

```
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(0x18326cec4 0x18243da40 0x183173594 0x183c2f6a8 0x183c2f62c 0x102808230 0x10354cdc8 0x10354ee28 0x102807af8 0x102807278 0x102808e34 0x10354b824 0x10354cdc8 0x10354fc90 0x10355e1dc 0x10355ebc8 0x182e8917c 0x182e8bcec)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

**Comment by cesarbarone** [comment]
any workaround @jhoogeboom ?

**Comment by jhoogeboom** [comment]
Not really, if you find any, also interested.

**Comment by ggozad** [comment]
My guess is this comes from the ionic side since tests pass just fine on cordova. Could you please take it there?
