### ISSUE TITLE
Data is still accessible after loging out of icloud

### ISSUE THREAD

**Issue by cmartin81** [Crypho/cordova-plugin-secure-storage#171]
I'm storing an accesstoken with this plugin. This works good, but when I sign out of from my iphone with my Apple ID, the accesstoken is still accessible. Why is this? I thought this plugin was storing values inside the keychain in icloud. And that signing out of icloud will also make my accesstoken dissapear.

I am also using this configuration: <preference name="KeychainAccessibility" value="WhenUnlocked" />

**Comment by ggozad** [comment]
The plugin is no-longer maintained closing all issues that are not going to be resolved.
