### ISSUE TITLE
Refactor actions in static class so it can be re-used by other plugins

### ISSUE THREAD

**Issue by BorntraegerMarc** [Crypho/cordova-plugin-secure-storage#174]
So we wrote an own cordova plugin and wanted to re-use the "set" and "get" action: https://github.com/Crypho/cordova-plugin-secure-storage/blob/master/src/android/SecureStorage.java#L135

The problem was that in cordova we can't call this `execute` function from the native side. So we had to manually copy / paste the code from all the actions in order for us to use the functionality.

It would be really great if this plugin could expose some static methods which then can be re-used in other plugins.

I'm specifically talking about these methods:
https://github.com/Crypho/cordova-plugin-secure-storage/blob/master/src/android/SecureStorage.java#L113-L162

I can provide  a PR for this if you guys are interested

**Comment by ggozad** [comment]
The plugin is no-longer maintained closing all issues that are not going to be resolved.
