### ISSUE TITLE
Capacitor support

### ISSUE THREAD

**Issue by BorntraegerMarc** [Crypho/cordova-plugin-secure-storage#177]
Hi

I wanted to get feedback from the authors & maintainers whether you are open (or even planning?) to support ionic's capacitor? https://capacitor.ionicframework.com/docs/plugins/

I think generally Cordova plugins should work out of the box and I will test in the following weeks whether there are any issues. But wants to get some feedback from you guys :)

Now since capacitor is stable (https://blog.ionicframework.com/announcing-capacitor-1-0/) it would be a good time to start thinking about it.

Looking forward to get feedback :)

**Comment by ggozad** [comment]
The plugin is no-longer maintained closing all issues that are not going to be resolved.
