### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by softBarbarian** [Crypho/cordova-plugin-secure-storage#19]
Hello @ggozad i am wondering if you could take few moments and explain the differences (as far as security goes) between your plugin and https://github.com/shazron/KeychainPlugin plugin?

Thanks a lot in advance.

Thanks

**Comment by ggozad** [comment]
There's very little difference between the two plugins on iOS. They both provide an API to access the keychain.
In ``cordova-plugin-secure-storage`` we also implemented the same API for android as described in the README.

**Comment by softBarbarian** [comment]
@ggozad thanks a lot for prompt reply
