### ISSUE TITLE
Error on Android 6.0 Marshmallow

### ISSUE THREAD

**Issue by mattalco** [Crypho/cordova-plugin-secure-storage#20]
When using this plugin, we occasionally get the following error on Android 6.0 devices. I've posted our log below of the error - any ideas on what's causing this?

`02-09 16:17:40.909 455 455 D keystore: Ran out of operation handles, trying to prune 0xb7744370

02-09 16:17:40.911 455 455 D keystore: Ran out of operation handles, trying to prune 0xb7747650

02-09 16:17:40.913 455 455 D keystore: Ran out of operation handles, trying to prune 0xb7746818

02-09 16:17:40.914 455 455 D keystore: Ran out of operation handles, trying to prune 0xb7741b38

02-09 16:17:40.915 455 455 D keystore: Ran out of operation handles, trying to prune 0xb7742850

02-09 16:17:40.916 21823 22871 E SecureStorage: Decrypt failed : 

02-09 16:17:40.916 21823 22871 E SecureStorage: javax.crypto.IllegalBlockSizeException 

02-09 16:17:40.916 21823 22871 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:486) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at javax.crypto.Cipher.d oFinal(Cipher.java:1502) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at com.crypho.plugins.RS A.decrypt(RSA.java:28) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at com.crypho.plugins.Se cureStorage$3.run(SecureStorage.java:79) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at java.lang.Thread.run( Thread.java:818) 

02-09 16:17:40.916 21823 22871 E SecureStorage: Caused by: android.security.KeyS toreException: Invalid operation handle 

02-09 16:17:40.916 21823 22871 E SecureStorage: at android.security.KeyS tore.getKeyStoreException(KeyStore.java:632) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunke dStreamer.java:132) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunk edStreamer.java:217) 

02-09 16:17:40.916 21823 22871 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:473) 

02-09 16:17:40.916 21823 22871 E SecureStorage: ... 6 more 02-09 16:17:40.917 21823 22872 E SecureStorage: Decrypt failed : 

02-09 16:17:40.917 21823 22872 E SecureStorage: javax.crypto.IllegalBlockSizeExc eption 

02-09 16:17:40.917 21823 22872 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:486) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at javax.crypto.Cipher.d oFinal(Cipher.java:1502) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at com.crypho.plugins.RS A.decrypt(RSA.java:28) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at com.crypho.plugins.Se cureStorage$3.run(SecureStorage.java:79) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at java.lang.Thread.run( Thread.java:818) $ toreException: Invalid operation handle 

02-09 16:17:40.917 21823 22872 E SecureStorage: at android.security.KeyS tore.getKeyStoreException(KeyStore.java:632) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunke dStreamer.java:132) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunk edStreamer.java:217) 

02-09 16:17:40.917 21823 22872 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:473) 

02-09 16:17:40.917 21823 22872 E SecureStorage: ... 6 more 

02-09 16:17:40.918 21823 23084 E SecureStorage: Decrypt failed : 

02-09 16:17:40.918 21823 23084 E SecureStorage: javax.crypto.IllegalBlockSizeExc eption 

02-09 16:17:40.918 21823 23084 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:486) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at javax.crypto.Cipher.d oFinal(Cipher.java:1502) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at com.crypho.plugins.RS A.decrypt(RSA.java:28) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at com.crypho.plugins.Se cureStorage$3.run(SecureStorage.java:79) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at java.lang.Thread.run( Thread.java:818) 

02-09 16:17:40.918 21823 23084 E SecureStorage: Caused by: android.security.KeyS toreException: Invalid operation handle 

02-09 16:17:40.918 21823 23084 E SecureStorage: at android.security.KeyS tore.getKeyStoreException(KeyStore.java:632) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunke dStreamer.java:132) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunk edStreamer.java:217) 

02-09 16:17:40.918 21823 23084 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:473) 

02-09 16:17:40.918 21823 23084 E SecureStorage: ... 6 more 

02-09 16:17:40.919 21823 22874 E SecureStorage: Decrypt failed : 

02-09 16:17:40.919 21823 22874 E SecureStorage: javax.crypto.IllegalBlockSizeExc eption 

02-09 16:17:40.919 21823 22874 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:486) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at javax.crypto.Cipher.d oFinal(Cipher.java:1502) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at com.crypho.plugins.RS A.decrypt(RSA.java:28) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at com.crypho.plugins.Se cureStorage$3.run(SecureStorage.java:79) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at java.lang.Thread.run( Thread.java:818) 

02-09 16:17:40.919 21823 22874 E SecureStorage: Caused by: android.security.KeyS toreException: Invalid operation handle 

02-09 16:17:40.919 21823 22874 E SecureStorage: at android.security.KeyS tore.getKeyStoreException(KeyStore.java:632) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunke dStreamer.java:132) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunk edStreamer.java:217) 

02-09 16:17:40.919 21823 22874 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:473) 

02-09 16:17:40.919 21823 22874 E SecureStorage: ... 6 more 

02-09 16:17:40.920 21823 23086 E SecureStorage: Decrypt failed : 

02-09 16:17:40.920 21823 23086 E SecureStorage: javax.crypto.IllegalBlockSizeExc eption 

02-09 16:17:40.920 21823 23086 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:486) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at javax.crypto.Cipher.d oFinal(Cipher.java:1502) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at com.crypho.plugins.RS A.decrypt(RSA.java:28) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at com.crypho.plugins.Se cureStorage$3.run(SecureStorage.java:79) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at java.util.concurrent. ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at java.lang.Thread.run( Thread.java:818) 

02-09 16:17:40.920 21823 23086 E SecureStorage: Caused by: android.security.KeyS toreException: Invalid operation handle 

02-09 16:17:40.920 21823 23086 E SecureStorage: at android.security.KeyS tore.getKeyStoreException(KeyStore.java:632) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunke dStreamer.java:132) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at android.security.keys tore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunk edStreamer.java:217) 

02-09 16:17:40.920 21823 23086 E SecureStorage: at android.security.keys tore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.jav a:473) 

02-09 16:17:40.920 21823 23086 E SecureStorage: ... 6 more
`

**Comment by demetris-manikas** [comment]
Hi, for the time being I can only guess.
Searching on google for the  keystore: Ran out of operation handles, trying to prune... 
lead me to https://android.googlesource.com/platform/system/security/+/1f76969bd8b6179f256dafb938bb458bc997c23d%5E!/
where I could see that it seems that one cannot have more than 15 concurrent keystore operations.
Could that be the case for you?

**Comment by mattalco** [comment]
Hi, thanks so much for responding.

The case you mention above about the 15 concurrent operations should not affect what we are doing. It's been strange that everything has worked for several months with no changes to this code until we started testing it on Marshmallow. Then we started seeing these crashes on a pretty regular basis.

**Comment by ggozad** [comment]
Would it be possible to provide a consistent test case? And run it on an emulator?

**Comment by mattalco** [comment]
Hello again, I'm working to get that sample app you mentioned up and running.

In the meantime, I did some more searching and came across this link: http://stackoverflow.com/questions/34286798/javax-crypto-cipher-working-differently-since-android-6-marshmallow

It seems some things with Android in version 6 changed with regards to the Cipher.

**Comment by leecrossley** [comment]
I have been testing on Marshmallow (6.0.1) today (Nexus 7) and have not experienced this issue (yet)

**Comment by mattalco** [comment]
We have been unable to reproduce after working with this more. Thank you both for looking into this :)
