### ISSUE TITLE
Is it possible to use this plugin and iOS keychain to automatically login to Cordova app?

### ISSUE THREAD

**Issue by lumierephoto** [Crypho/cordova-plugin-secure-storage#21]
I'm looking for a possible solution to login to a Cordova iOS app automatically using the iOS keychain. 

Is this possible? Can this plugin help?

I've tried looking at Shazron's KeychainPlugin, but his example only shows playing with getting, setting and deleting the keys for predefined values. 

How can this plugin use the values in the keychain already? Is there a simple example of how this can be done? I can't find this info anywhere. At least not for a Cordova project.

Any help would be great!

**Comment by ggozad** [comment]
You can store credentials/a session/whatever in the keychain and use them to log in. i.e. you have the user log in once and then store the credentials.
