### ISSUE TITLE
phonegap build plugin id

### ISSUE THREAD

**Issue by gorkagb** [Crypho/cordova-plugin-secure-storage#26]
Hi,
We are using phonegap build with angularjs for one of our hybrid apps. 

We are trying to integrate the plugin using this version https://build.phonegap.com/plugins/3403 and we are getting the same issue as in https://github.com/Crypho/cordova-plugin-secure-storage/issues/13 because the plugin id in securestorage.js is not correct:
var sjcl_ss = cordova.require('com.crypho.plugins.securestorage.sjcl_ss') where it should be
var sjcl_ss = cordova.require('com.m2phear.plugins.securestorage.sjcl_ss')

Is there any chance the phonegap plugin will be updated any time soon? any alternatives?

Thanks in advance

**Comment by ggozad** [comment]
Hey,
You are using one of the broken forks instead of the original (hint: this is the repo of the original).
Seems that the plugin you are using has only one change from our original, changing the namespace.
I cannot control the forks nor fix them.

You could also kindly ask @nespapu to remove his broken plugin as it just causes confusion.

**Comment by gorkagb** [comment]
Hi again, thanks for replying so soon

Sorry then, we tried using the original plugin "com.crypho.plugins.securestorage", added to config.xml but phonegap build states is an invalid plugin when trying to rebuild.

The correct one is this https://build.phonegap.com/plugins/5851 ?

I´ll get in touch with @nespapu to ask for removal of his plugin

**Comment by ggozad** [comment]
You should be using npm to manage your plugins. Crypho is publishing all releases to the npm registry. The version you indicate is old (we are now on 2.2.2) and build.phonegap.com is deprecated.

I am not using phonegap, but I know others have managed just fine so I am guessing it's a configuration problem. If you post details about what you do and how it fails, I might be able to help.

**Comment by gorkagb** [comment]
changed to the version from npm you quoted and seems to be working now, thanks again!

**Comment by gorkagb** [comment]
Sorry for reopening the issue but i´m having some misconceptions with how the plugin works.
Once the plugin is instantiated, initialized, for every ss.get do we need to use the success callback in order to manage the data? 

Being aysncronous is giving us headaches for how we managed localstorage inside our app (angularjs) previously so maybe i´m looking at it from a completely wrong perspective and need to change the point of view. Should we only use the plugin at start of app to setup values in rootscope and before closing it to store them again if needed?

**Comment by ggozad** [comment]
Cordova plugins unfortunately need to be async. That's how the bridge works.
With that in mind it's not that hard to rethink your app that way. For our own apps we use promises to avoid callbacks.

You are also correct that typically you would read whatever data you need when initialising the app or a some view. If you need a lot of secure data, you might as well store only keys in securestorage and encrypt/decrypt on the client synchronously.

**Comment by gorkagb** [comment]
ok, thanks a lot for the advice.

**Comment by nespapu** [comment]
Hi @ggozad and @gorkagb I have just deleted the repository as you asked.
