### ISSUE TITLE
Why use JS sjcl library to do the AES instead of use Android Java API

### ISSUE THREAD

**Issue by yyfearth** [Crypho/cordova-plugin-secure-storage#27]
As I saw in some forks, they are using Android API to do the AES encryption/decryption instead of doing such using JavaScript.
Since JavaScript AES implementation usually slower and also blocking (sync) unless put it into web worker.

I guess, maybe the author just need to support Android with a quick solution, but not care about performance that much?

**Comment by ggozad** [comment]
Android does not have an equivalent of the iOS keychain. The current implementation works for the purposes we wanted it to. Of course a native implementation would be better. Please make a pull request and I will happily accept it.

**Comment by ggozad** [comment]
Gonna reopen this since @demetris-manikas has submitted crypho/cordova-plugin-secure-storage#29.
Please discuss there and contribute.
