### ISSUE TITLE
iOS synchronization?

### ISSUE THREAD

**Issue by j3k0** [Crypho/cordova-plugin-secure-storage#32]
Can we assumed data stored using the plugin will be synchronized between iOS devices sharing the same Apple ID? (I know KeyChain allows this)...

The documentation doesn't mention whether or not synchronization is enabled, and/or possible to setup.

Thanks!

**Comment by ggozad** [comment]
It really depends how you setup your app to allow or disallow this, the plugin does set this for you. My guess is it should work just fine if you and the user allow it.
If you experiment with this perhaps you can share your experience as a PR in the README?
