### ISSUE TITLE
Android question: how to keep data in storage even when app is deleted

### ISSUE THREAD

**Issue by yugidazai** [Crypho/cordova-plugin-secure-storage#38]
Hi,

Firstly thanks for your work for this plugin.
It works perfectly for iOS, as data is stored in keychain regardless the app is deleted.

However, as you mention in README file, data is encrypted and stored in `localStorage` only in case of Android. It means that data will be deleted when you remove app.
Is there any way so that this plugin can do the same logic as iOS?

Thanks in advance.

**Comment by ggozad** [comment]
There is definitely room for improvement in this area. I don't have the answer but would be happy to accept a PR...

**Comment by demetris-manikas** [comment]
@ggozad Well... is it possible?. On android uninstalling the app causes the RSA key used by the app to be deleted from the KeyStore thus making all the contents of the secure-storage useless. 
Now that we use SharedPreferences there seems to exist a way of backing up and restoring data between uninstallation installation of an app so maybe a password based secure-storage would solve the issue (say by encrypting the RSA keys with the password and storing them in SharedPreferences).

Any more ideas?

**Comment by ggozad** [comment]
I would not build such an elaborate mechanism for a single platform. In addition it is dubious to assume that if a user uninstalls an app he would like his secrets to remain.
I think it is safe to close this as I don't see it implemented in any way in the foreseeable future.

**Comment by javahemans** [comment]
@ggozad So this plugin does not store data permanently on Android ?
