### ISSUE TITLE
Is there a way to 'remove all' or 'clear' storage?

### ISSUE THREAD

**Issue by stephenliberty** [Crypho/cordova-plugin-secure-storage#41]
As the title says, I'm looking for a way to 'clear' the storage - either by destroying the one that exists or wiping out all the values from it. Is that possible?

(I'm aware that in its current form the answer is no, I'm more curious about whether it can be made to happen)

**Comment by ggozad** [comment]
It's trivial to enumerate as well as clear all keys. A pull request would be most welcome.
