### ISSUE TITLE
question regarding Keys

### ISSUE THREAD

**Issue by charlesmccann** [Crypho/cordova-plugin-secure-storage#43]
Thanks again for building this.  

Is it safe to have the Key be a string in our app's javascript code?
i.e. if the key is "password" and I store the user's password in the value, does that make it easier for someone to hack the password if the phone is compromised? 

And is someone able to look at the list of "keys"? 
Thank you!

**Comment by demetris-manikas** [comment]
@charlesmccann  obfuscation is by no means secure therefore it does not matter how you name a key. 
You should consider keys to be public. Don't store sensitive information on a key this is what values are for.

**Comment by ggozad** [comment]
@charlesmccann yes it is relevant what the key is called. It's the value that is encrypted. You can call it "password" or whatever you like.
