### ISSUE TITLE
Device is not secure

### ISSUE THREAD

**Issue by OmarHassan25** [Crypho/cordova-plugin-secure-storage#44]
I am getting this error on android when trying to use the plugin, "Device is not secure",
Here is my implementation:
`
import { SecureStorage } from 'ionic-native';
import {Constants} from '../../model/Constants';

export class SecStorage {

    static instance: SecStorage;
    static isCreating: Boolean = false;
    private secureStorage: SecureStorage;

    public static LOGGED = "LOGGED";
    public static TokenId = "TOKEN_ID";

    constructor() {
        if (!SecStorage.isCreating) {
            throw new Error("You can't call new in Singleton instances!");
        }
    }

    static getInstance() {
        if (SecStorage.instance == null) {
            SecStorage.isCreating = true;
            SecStorage.instance = new SecStorage();
            SecStorage.instance.init();
            SecStorage.isCreating = false;
        }

        console.log("INSTANCE -> " + SecStorage.instance);
        return SecStorage.instance;
    }

    private init() {
      ;debugger
        this.secureStorage = new SecureStorage();
          ;debugger
        this.secureStorage.create(Constants.SECURE_STORAGE_KEY)
            .then(
            () => console.log('*SECURE STORAGE SUCCESS*'),
            error => console.log("*SECURE STORAGE ERROR*" + error)
            );
    }

    getValue(key) {
        return this.secureStorage.get(key);
    }

    setValue(key, value) {
        this.secureStorage.set(key, value)
            .then(
            data => console.log(data),
            error => console.log(error)
            );
    }

    removeValue(key) {
        this.secureStorage.remove(key);
        // .then(
        // data => console.log(data),
        // error => console.log(error)
        // );
    }

}
`

Can i Know what is wrong ?

**Comment by ggozad** [comment]
As of the last version, if the device has no screen lock or an screen lock with insufficient security that error is thrown. There is an example in the README, you should the user and call ``secureDevice`` to bring up the screen lock settings.

**Comment by OmarHassan25** [comment]
Can't we skip this security check?

**Comment by ggozad** [comment]
Please read the docs. No you can't, we cannot store anything on the credential storage unless appropriate screen lock settings are there.

**Comment by ezamelczyk** [comment]
Could you maybe provide a function to check if device is secure?

**Comment by ggozad** [comment]
@ezamelczyk Isn't that what ```init()``` does?

**Comment by ezamelczyk** [comment]
@ggozad Yeah, you're right! Thanks.
