### ISSUE TITLE
Gettinf "Failed to Load Error"

### ISSUE THREAD

**Issue by pallaviMN** [Crypho/cordova-plugin-secure-storage#45]
Hi Team,

I am using Samsunf 4.1 device & i am getting below error

KeyStore.PrivateKeyEntry keyEntry = getKeyStoreEntry(alias);
		if (keyEntry == null) {
			throw new Exception("Failed to load key for " + alias);
		}

**Comment by ggozad** [comment]
Could you please run the tests on the device (see README) and let me know if you get any failures?

**Comment by kukikiloke** [comment]
I also got the same error on Samsung S3 running Cyanogen 13 (6.0.1) when rebuilding the app with cordova client. It works fine when building with Android Studio or close-and-relaunch the app on the device.

To me, it looks me some error occurred when trying to recover the keystore.

**Comment by ggozad** [comment]
Unless one of you can reproduce and debug I will not be able to help. If you can consistently reproduce please make a test case that I can use.

**Comment by kukikiloke** [comment]
**Update:**

I was using cordova-android 5.0.0 when I was encountering this issue, upgrading it to 5.1.1 solved the problem.

Fix for [CB-9557](https://issues.apache.org/jira/browse/CB-9557) in 5.0.0 introduced this bug [CB-10157](https://issues.apache.org/jira/browse/CB-10157) which will uninstall the app first before reinstalling the app. Version 5.1.1 fixed that.

**Comment by ggozad** [comment]
@kukikiloke, that seems it could be the problem. @pallaviMN could you tell us if this would be the case for you too?

Remember also: You ALWAYS need to init the storage, is that the case?
