### ISSUE TITLE
no exported member 'SecureStorage'. 

### ISSUE THREAD

**Issue by endriazizi** [Crypho/cordova-plugin-secure-storage#50]
Hello there!

I am using cordova secure storage on my ionic 2 app,

I got this error:
```
TypeScript error: /Users/endriazizi/Documents/Project/app/app/pages/oauth/oauth.
service.ts(7,10): Error TS2305: Module '"/Users/endriazizi/Documents/Project/app
/node_modules/ionic-native/dist/index"' has no exported member 'SecureStorage'.                 
TypeScript error: app/app.ts(12,10): Error TS2305: Module '"/Users/endriazizi/Documents/Project/
app/node_modules/ionic-native/dist/index"' has no exported member 'SecureStorage
```

in my package.json:

 "cordova-plugin-facebook4",
    "cordova-plugin-device@~1.1.2",
    "cordova-plugin-console@~1.0.3",
    "cordova-plugin-whitelist@~1.2.2",
    "cordova-plugin-statusbar@~2.1.3",
    "ionic-plugin-keyboard@~2.2.1",
    "cordova-plugin-splashscreen@~3.2.2",
    "cordova-plugin-secure-storage@~2.4.1",
    "cordova-plugin-inappbrowser@~1.4.0",
    "cordova-plugin-geolocation@~2.2.0",
    "cordova-plugin-facebook4@~1.7.1"

I don't know what to do

Can someone help me?
<img width="719" alt="screen shot 2016-08-27 at 19 00 52" src="https://cloud.githubusercontent.com/assets/9431994/18028859/c5099e9c-6c88-11e6-90bb-cab7373ea476.png">

**Comment by ggozad** [comment]
This seems like an issue with your config. I am afraid there's not much I can do to help you here.
