### ISSUE TITLE
Android keystore deletion on security setting change

### ISSUE THREAD

**Issue by kblum** [Crypho/cordova-plugin-secure-storage#53]
Changing the lock screen type on Android erases the keystore (issues [61989](https://code.google.com/p/android/issues/detail?id=61989) and [210402](https://code.google.com/p/android/issues/detail?id=210402)). The author of the second issue also describes it in the [Android Security: The Forgetful Keystore](https://doridori.github.io/android-security-the-forgetful-keystore/) blog post. This means that the keystore can only be used as a credential cache and not persistent storage.

This issue also exists in Android 6.0 for keys that require encryption. Details from [Android Keystore Changes](https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-network):

> Keys which do not require encryption at rest will no longer be deleted when secure lock screen is disabled or reset (for example, by the user or a Device Administrator). Keys which require encryption at rest will be deleted during these events.

I assume this means that keys stored using the plugin on Android will be lost if the user changes their lock screen type, is this correct? If so, this should probably be mentioned explicitly in the documentation.

**Comment by ggozad** [comment]
Indeed this is the case. secure-storage is not meant to be used as a full-blown storage, rather as a convenient and secure way to store secrets.
Would you mind updating the docs in a PR?

**Comment by kblum** [comment]
Will do.
