### ISSUE TITLE
"cordova.plugins.SecureStorage is not a constructor"

### ISSUE THREAD

**Issue by itsJaeger** [Crypho/cordova-plugin-secure-storage#57]
09-22 18:12:43.521 13324-13324/? I/chromium: [INFO:CONSOLE(65)] "Uncaught TypeError: cordova.plugins.SecureStorage is not a constructor", source: file:///data/user/0/com.adobe.phonegap.app/files/phonegapdevapp/www/js/index.js (65)

i'm pretty new at devloping in phonegap. so any advise would be appreciated.
when i try to create a phonegap storage instance via your walkthrough:

"		var ss = new cordova.plugins.SecureStorage(
			function () { console.log('Success')},
			function (error) { console.log('Error ' + error); },
			'my_app');

"

it stops the function and nothing after it is called. strange error though, i would assume the constructor is fine? :S

**Comment by ggozad** [comment]
My guess is the module is not registered properly, something with your config...

**Comment by itsJaeger** [comment]
Yeah i was thinking the same sir. so i checked my config, and confirmed the plugin is set in it
https://gyazo.com/b6f71a18ece21f287358e35391996bab
screenshot is attached of my config. 
can you think of anything i did wrrong? i just added it via cordova
"cordova plugin add cordova-plugin-secure-storage --save"

**Comment by ggozad** [comment]
Looks good to me. I have never used phonegap only vanilla cordova, so there might easily be something I am missing. Will leave this open in case somebody else can enlighten us :)

**Comment by itsJaeger** [comment]
if you ever have time to test on phone gab it would be appreciated T_T i wouldnt know where to begin to try troubleshooting this, or do you have any other tips so i can narrow it down?

**Comment by ggozad** [comment]
Could there be another place where the module is exported? Like window.plugins or something? Try with a debugger on the browser and see if phonegap registers plugins somewhere else perhaps.

**Comment by itsJaeger** [comment]
i should mention im debugging this app for android. 
it seems to work perfectly in the browser.

**Comment by demetris-manikas** [comment]
Your config specifies minsdk to 14 whilst SDK 19 is required to use the secure storage plugin. Can you try with minsdk 19 and report back?

**Comment by itsJaeger** [comment]
I spoke to the team at phonegap guys, apparently, the desktop app does not support any third party plugins. i appreciate the help :)
