### ISSUE TITLE
android security without lockscreen?

### ISSUE THREAD

**Issue by flieks** [Crypho/cordova-plugin-secure-storage#60]
What if they don't have want a lockscreen?
Is there a better alternative to base64 encoding to localStorage ?

Greetings

**Comment by ggozad** [comment]
Base64 encoding to localStorage:
https://www.youtube.com/watch?v=mcEyglpYuCk

Please don't be silly as explained in the doc, the lockscreen is required to have access to the relevant crypto.

**Comment by flieks** [comment]
sorry, i modified the question which is: Is there something better then base64 ? As it's quite insecure..
