### ISSUE TITLE
Code Sync issue after plugin installation

### ISSUE THREAD

**Issue by sagarhiremath6** [Crypho/cordova-plugin-secure-storage#62]
I have no idea whether this issue is exactly issue of this plugin or not. But since I am facing this issue after installing plugin, I wanna know the fix:

I have phone gap folder which has folder **www** and it had certain html, js files. After that I added android platform, in result **android** folder got created under **platforms** folder.

After that I added some files to android folder. Everything was fine till I install this plugin under phonegap folder.

As soon as this plugin got installed, I lost android specific files under **android** folder.

I am wondering what could be the issue and trying to recover files. Please help me.

**Comment by ggozad** [comment]
This has nothing to do with the plugin.
Please read the docs on cordova/phonegap.

Hint: you don't add ANYTHING under the platforms folder. The folder is recreated when you build and changes will be lost.
