### ISSUE TITLE
(Android 4.4.2 -4.4.4) AndroidKeyStore deleted after changing screen lock type or Clear credentials

### ISSUE THREAD

**Issue by SajevLucksman** [Crypho/cordova-plugin-secure-storage#63]
if we change the screen lock ( from PIN to Password for example ), the AndroidKeyStore is recreated empty and the previous generated key-pair are deleted. Couldn't retrive the old value after that.
plugin throws an error : error:0407106B:rsa routines:RSA_padding_check_PKCS1_type_2:block type is not 02

**Comment by ggozad** [comment]
Indeed this is the case, but I do not see how to go around that as it is the android's keystore that is reset. This lies outside of the control of the app or the plugin.
Unless you have some idea about fixing this, let me know so that I can close the issue.

**Comment by SajevLucksman** [comment]
According to this google bug id https://code.google.com/p/android/issues/detail?id=61989 .         Its recreated on Android 5.0, 5.01 as well but in Android 6 its working fine.Is there any way to replace android keystore ? Such as JKS , Bouncy Castle , [SpongyCastle](https://github.com/rtyley/spongycastle)   ?

**Comment by ggozad** [comment]
While I would not refuse a well done PR on this, I would like to keep the android cost on this plugin to an acceptable level. At the moment the android part is way more complex than its iOS and windows counterparts, and already contains two upgrade paths. I would really like to avoid the extra maintenance cost on this further upgrade paths etc.

**Comment by ggozad** [comment]
Closing this, but if you do make a PR using an alternative to keystore, I will be happy to review. IMHO not worth it.
