### ISSUE TITLE
Is there a way to get all keys of one namespaced storage?

### ISSUE THREAD

**Issue by yyfearth** [Crypho/cordova-plugin-secure-storage#64]
For localStorage we can use `Object.keys(localStorage)` to get keys of all stored entries.
But this plugin seem like does not have this function.

Another important function might be needed is `clear()` since iOS never clean up keychain items even after app been uninstalled. But if I can get all the keys, I can implement that easily.

Update: seems like implement `reset`/`clear` function natively is much easier than enumerate stored keys.

**Comment by ggozad** [comment]
A pull request will be welcome, I am sure others will chime in and provide android/windows support.

**Comment by demetris-manikas** [comment]
The keys method is already implemented for android. It only needs to be exposed.

**Comment by yyfearth** [comment]
@demetris-manikas cool, I saw both keys and clear are implemented for android.
Let me try to add iOS implementation and expose them.

I'm not sure how to unit test cordova plugin yet, I will try testing after I make them works.

**Comment by yyfearth** [comment]
@ggozad I'm working on my branch which added `keys` and `clear` methods, and I will give you a PR after my code been tested.  https://github.com/yyfearth/cordova-plugin-secure-storage/commits/feat-clear-keys

Since it is my first time to write ObjC code, I'm not that confident before somebody else tested my code.

@demetris-manikas I have exposed it in my branch https://github.com/yyfearth/cordova-plugin-secure-storage/commit/2f7144a70f5317e72673fb3604737b3beeaca902

@sgrebnov Hi, since you have implemented the windows version, could you help me check my newly added code works or not? https://github.com/yyfearth/cordova-plugin-secure-storage/commit/80cbba2f87da9e01258645132f903d93ad240d50
I have no experience to write code for windows 10 before, and I do not have any environment setup for me to test it either.

**Comment by ggozad** [comment]
I will review everything once you are done, there's a first time for everybody nothing to worry about :)
Please make sure you add a test that the others can test against too.
