### ISSUE TITLE
Android 5.1.1 - Appending "_SS_" value with the key.

### ISSUE THREAD

**Issue by SajevLucksman** [Crypho/cordova-plugin-secure-storage#65]
Android 5.1.1 i have observed an issue from javascript passed key value "test/user" but i am getting an error message like  "error: Error: Key [_SS_test/user] not found. ". Seems inside the android native code it's appending "_SS_" value with the key value.

**Comment by ggozad** [comment]
The _SS_ prefix is a remnant from the time we were using localStorage. I am not sure if I understood, does this cause an issue for you?

**Comment by SharkChips** [comment]
Also I believe the browser platform still uses localStorage.
