### ISSUE TITLE
iCloud syncing not optional

### ISSUE THREAD

**Issue by spaceagestereo** [Crypho/cordova-plugin-secure-storage#67]
SAMKeychainQuery.synchronizationMode is set by default SAMKeychainQuerySynchronizationModeAny which later sets kSecAttrSynchronizable to kSecAttrSynchronizableAny. I have some code but am not an Objective C expert. I did step through the debugger in XCode and it looks like my code is correctly setting the value of kSecAttrSynchronizable to "@NO". I wasn't sure if it was ok to do a PR against this repo so I here are the links to my commits. Please review and let me know if I can do a PR against this repo. Thanks!
https://github.com/spaceagestereo/cordova-plugin-secure-storage/commit/518cdc8b0a3824eed64ff6c09cc8b7b611d74e80

Fixed icloudsync variable name type:
https://github.com/spaceagestereo/cordova-plugin-secure-storage/commit/a09d523efa268e4c4e578a2149bae2ae876c008b

**Comment by ggozad** [comment]
I would love it if you turned this into a proper pull request. That would mean document the options possible and how to set them and tests. Do not worry about reviewing ahead of the PR, we can take it as we go. Note that atm I am stumped with all sorts of things so I will take some time.

**Comment by spaceagestereo** [comment]
@ggozad thanks for the feedback, I will do my best. This is my first time actually contributing on a project on GitHub. Thanks for all your work on this plugin!

**Comment by ggozad** [comment]
Welcome to the open-source club 👍 I hope you will find it as gratifying as I have :)

**Comment by ggozad** [comment]
Any news on this? I am reluctant to close it as I would like to have a proper PR.

**Comment by dcousens** [comment]
Does this imply iCloud backups are on by default right now?

**Comment by ggozad** [comment]
@dcousens it does.

**Comment by dcousens** [comment]
@ggozad out of interest,  what does an iCloud backup even mean if it is `DeviceOnly`?

**Comment by ggozad** [comment]
@dcousens my guess is that then no backup is taking place.

**Comment by demetris-manikas** [comment]
KeychainAccessibility is the config option. Values not ending in ThisDeviceOnly provide iCloud storage only when encrypted backups are in use. 
We might need to mention this in the readme. 
Anyway I believe this thread should close.
