### ISSUE TITLE
Set returns an error

### ISSUE THREAD

**Issue by soniyj** [Crypho/cordova-plugin-secure-storage#69]
Hello All,

Trying to save it using the simulator but I get always this error.

Error: Failure in SecureStorage.set() - Refer to SecBase.h for description

What to do?

**Comment by SharkChips** [comment]
This is an issue with the iOS simulator. See #48 for more details.

**Comment by ggozad** [comment]
Yes, this is a simulator issue.

**Comment by soniyj** [comment]
Ok so if I test it on a real device is going to work? I will test it.

**Comment by jordins** [comment]
I can confirm that fails in an emulator but works in a real device.

**Comment by soniyj** [comment]
great thanks I totally forgot to write a comment on it, that I can confirm as well.
