### ISSUE TITLE
Storing objects should either be supported cross-platform or not supported on Android

### ISSUE THREAD

**Issue by kamilbrk** [Crypho/cordova-plugin-secure-storage#70]
Hi,

It seems like that storing objects as a value works on Android, even though it shouldn't be supported.

One of our developers implemented the plugin on Android platform, but it failed testing on iOS due to the underlying issue. Looks like the cordova plugin is not capable of type checking on .set() and does not use NSDictionary behind the scenes in SAMKeychain library.

So, I'd suggest to implement a type checking and deny the use of objects whatsoever, especially since readme document only mention strings across the board.

Yet to test this on UWP.

Obviously, a quick workaround is to use JSON.stringify() and JSON.parse() for the value, which works perfectly.

Thanks!

**Comment by ggozad** [comment]
You are right, in our own app I do the json workaround. A pull request would be most welcome.

**Comment by ggozad** [comment]
We now check for strings only
