### ISSUE TITLE
TypeError: Cannot read property 'SecureStorage' of undefined

### ISSUE THREAD

**Issue by lazy-ape** [Crypho/cordova-plugin-secure-storage#71]
Hi,
I have a problem when I use it. The code like this:
```
 this.secureStorage = new SecureStorage();
    this.secureStorage.create(Config.storage_user_info_name).then(() => {
      console.log("secureStorage create success.");
    }, (error) => {
      console.log("secureStorage create error:" + error);
    });
```

when invoke the `create` method have a error like the title, how can I solve it? Thanks!

**Comment by ggozad** [comment]
Please read the docs. SecureStorage is namespaced and can be found under cordova.plugins

**Comment by guimabdo** [comment]
Actually this error is not exactly related to this plugin, but to an ionic2 plugin which wraps it.
Link: https://ionicframework.com/docs/v2/native/secure-storage/

You can resolve it by waiting for the ionic platform to be ready (Platform.ready() Promise) before instantiating the SecureStorage.
