### ISSUE TITLE
Calling get() multiple times in a row fails on certain Android devices.

### ISSUE THREAD

**Issue by ggozad** [Crypho/cordova-plugin-secure-storage#75]
Added a test on the FIX-multiple-calls-android branch.
Tests pass on say emulator. The newly added test and sometimes the test that does 2 sets/gets in a row fail on a Galaxy S6 running android 6.0.1. /cc @demetris-manikas

**Comment by demetris-manikas** [comment]
Unfortunately I cannot reproduce the error on my Galaxy S5 running android 6.0.1. 
Maybe you have to get rid of your S6 and get the S7 (oxoxo).

**Comment by ggozad** [comment]
From ``adb logcat``

```
11-17 14:28:39.197 14795 15211 E SecureStorage: Decrypt (RSA/AES) failed :
11-17 14:28:39.197 14795 15211 E SecureStorage: javax.crypto.IllegalBlockSizeException
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:486)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at javax.crypto.Cipher.doFinal(Cipher.java:1502)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at com.crypho.plugins.RSA.decrypt(RSA.java:28)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at com.crypho.plugins.SecureStorage$3.run(SecureStorage.java:126)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at java.lang.Thread.run(Thread.java:818)
11-17 14:28:39.197 14795 15211 E SecureStorage: Caused by: android.security.KeyStoreException: Invalid operation handle
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:944)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
11-17 14:28:39.197 14795 15211 E SecureStorage: 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:473)
```

**Comment by demetris-manikas** [comment]
#20 looks like a similar error.

**Comment by ggozad** [comment]
Fixed in #76, preferably it should have been done within the native part, but java...

**Comment by demetris-manikas** [comment]
#76 doesn't make sense to me, I believe it just hides another problem or bug. 
Why fix only get and not set?
There is no reason why only one thread can decrypt but many can encrypt.
And for god sake java is not the problem here. 
The code should be asynchromous and it was written this way on purpose.
If you wish to turn the android code to synchronous just remove threading from SecureStorage.java.
Has anyone reported problems on phones different from Samsung 6?

**Comment by ggozad** [comment]
This is indeed the case, hence the note that this should be fixed in the android part.
The problem manifests only during decryption, which is why we only throttle then.
The problem appears in many different phones. I personally checked with S7 and a few others all running 6.0.1, it appears in most of them. 
I will be happy to remove the queue, but it is obvious that this will happen only when the native part works as expected.

**Comment by demetris-manikas** [comment]
Then it is much simpler to just add the synchronized keyword to the declarations of the encrypt, decrypt methods of the RSA.java and AES.java.
