### ISSUE TITLE
ionic 2 SecureStorage does not store any data

### ISSUE THREAD

**Issue by walaa118** [Crypho/cordova-plugin-secure-storage#77]
this errors occur when i try to use  SecureStorage  in ionic 2 project with visual studio:

create error : Error: Device is not secure
get error : Error: Key [_SS_myitem] not found.
set error : Error: Failed to load key for io.cordova.myappb0bf2a.my_store_name

  platform.ready().then(() => {

    let secureStorage: SecureStorage = new SecureStorage();
    secureStorage.create('my_store_name')
        .then(
        () => console.log('Storage is ready!'),
        error => console.log("create error : "+error)
        );

    secureStorage.get('myitem')
        .then(
        data => console.log("get data : "+data),
        error => console.log("get error : "+error)
        );

    secureStorage.set('myitem', 'myvalue')
        .then(
        data => console.log("set data : "+data),
        error => console.log("set error : "+error)
        );

    secureStorage.remove('myitem')
        .then(
        data => console.log("remove data : "+data),
        error => console.log("remove error : "+error)
        );
    });
  
what is wrong?

**Comment by ggozad** [comment]
Please read the docs.
