### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by aitor007in** [Crypho/cordova-plugin-secure-storage#80]
Hi, 
I have tried to implement the plugin, but when I do a "get" of a variable that is not yet created in the keychain the application gives me an error:

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[NSBundle initWithURL:]: nil URL argument'
*** First throw call stack:
(0x224a9b0b 0x21c66dff 0x224a9a51 0x22c6d2e1 0x22c6d277 0xd5e63 0x3a17a9 0xd5659 0xd4e47 0xd15c1 0x3a0ba7 0x3aceff 0x3ac7f1 0x221dae0d 0x221da9fc)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

The error occurs in this class:

**SAMKeychainQuery.m** 

```
+ (NSError *)errorWithCode:(OSStatus) code {
	static dispatch_once_t onceToken;
	static NSBundle *resourcesBundle = nil;
	dispatch_once(&onceToken, ^{
		_**NSURL *url = [[NSBundle bundleForClass:[self class]] URLForResource:@"SAMKeychain" withExtension:@"bundle"];**_
		_**resourcesBundle = [NSBundle bundleWithURL:url];**_
	});
```

The url variable returns nil, if I implement an if the plugin works correctly.

I tried in iOS 10 and 9 versions , my application use angular and ionic frameworks.
	
Thank you

**Comment by ggozad** [comment]
How do you initialize the plugin?

**Comment by aitor007in** [comment]
Thanks for the quick reply:

```
  $rootScope.secureStorage = new cordova.plugins.SecureStorage(
                                                                  function () { console.log('Success')},
                                                                  function (error) { console.log('Error ' + error); },
                                                                  'myappname');
```

**Comment by ggozad** [comment]
I am not sure if I understand correctly but does your app crash?
When you try to get a key that does not exist, the error callback SHOULD be called, this is the expected behavior.

**Comment by aitor007in** [comment]
Yes, but if url returns null inside SAMKeychainQuery.m, the app crash, this can be solved adding if condition before set resourcesBundle 

`		_**NSURL *url = [[NSBundle bundleForClass:[self class]] URLForResource:@"SAMKeychain" withExtension:@"bundle"];**_
		_**resourcesBundle = [NSBundle bundleWithURL:url];**_`

**Comment by ggozad** [comment]
I will be happy to fix this but I think it would be a lot better if it was fixed in SAMKeychain. Would you mind submitting to https://github.com/soffes/SAMKeychain, then I will merge when it's done there.
