### ISSUE TITLE
How to check storage data after create namespaced storage

### ISSUE THREAD

**Issue by atukilham** [Crypho/cordova-plugin-secure-storage#83]
First, i created namespaced storage.
Then, before set key/value, i want to check first that key/value has been set before.
How can i do that?

Here sample code : 
```
// created  namespaced storage
var ss = new cordova.plugins.SecureStorage(
             function () { console.log('Success')},
             function (error) { console.log('Error ' + error); },
    'my_app');

//set variabel
var data;

// Get a key's value from the storage
ss.get(
    function (value) { 
              data = true;             
     },
   function (error) {
             data = false;
   }'mykey');

// Checking
if(data == true){
      //next proccess
}else{
     //set new key/value
}
```

I do that and my app was blank.
Anyone can help me, please?

**Comment by ggozad** [comment]
Unless you provide more info there really is no way to know if SS is even the culprit here. One thing to do is run ss.get only after initializing has succeeded.
