### ISSUE TITLE
Doesn't fallback to LocalStorage in the browser

### ISSUE THREAD

**Issue by karlbateman** [Crypho/cordova-plugin-secure-storage#89]
When running in the browser with `ionic serve` the storage is never created and thus the LocalStorage never used. Trying to set a value, results in an error.

The following sample app can used to simulate this https://github.com/karlbateman/debugApp.

**Comment by ggozad** [comment]
Do you initialize properly with ```new cordova.plugins.SecureStorage(success, error, 'domain');```
Is there an error during init?

**Comment by karlbateman** [comment]
Yep, see [here](https://github.com/karlbateman/debugApp/blob/master/src/app/app.component.ts#L39-L40). No errors on initialization.

**Comment by ggozad** [comment]
I am sorry but are you perhaps using something completely different to out plugin?
I see 
```
import { SecureStorage } from 'ionic-native';
```
and also we do not have a ```create()``` in the API.

**Comment by ggozad** [comment]
Oh I see Ionic has added support for our plugin. This is nice, it would be even nicer somebody would let me know too :)
My guess is that the wrapper they have made does not deal with browser, the browser platform is working fine on our plugin. Please create an issue with them and reference this one so that I also get informed :)

**Comment by karlbateman** [comment]
The Ionic documentation links to this repo? see https://github.com/Crypho/cordova-plugin-secure-storage. I am assuming that after running ionic plugin add `cordova-plugin-secure-storage` I am using your plugin?

**Comment by karlbateman** [comment]
Sure will do, thanks for the info ;-)

**Comment by ggozad** [comment]
Awesome :)
