### ISSUE TITLE
Errors are inconsistent between platforms

### ISSUE THREAD

**Issue by jvjvjv** [Crypho/cordova-plugin-secure-storage#91]
I am testing on iOS and Android, and it appears that if there is an error (e.g. object doesn't exist in secure storage), a string is returned in iOS but an object is returned in Android.

A new version should be created that resolves this issue by implementing a standardised error response among all platforms.

**Comment by ggozad** [comment]
@jvjvjv yep this is indeed the case, had forgotten to come back to this.

**Comment by ggozad** [comment]
Ops sorry, closed the wrong ticket:)

**Comment by ggozad** [comment]
There is a test that checks exactly that that passes fine on all platforms. 
```
        it('should call the error handler when getting a key that does not exist', function (done) {
            spyOn(handlers, 'errorHandler').and.callFake(function () {
                expect(handlers.successHandler).not.toHaveBeenCalled();
                done();
            });
            spyOn(handlers, 'successHandler');

            ss = new cordova.plugins.SecureStorage(function () {
                ss.get(handlers.successHandler, handlers.errorHandler, 'nofoo');
            }, handlers.errorHandler, SERVICE);
        });
````

Are you sure you haven't actually set an empty string?

**Comment by jvjvjv** [comment]
My issue came at getting a key that did not exist. In the error callback, iOS gives me the sentence, "The specified item could not be found in the keychain." Android returns, "Error: Key [_some ID_] not found."

They are completely different errors. I have to write an error handler that covers each platform I'm supporting, instead of writing a single error handler. That is why I requested a standardised error response. I don't even know what other errors exist anyway, so I cannot account for any errors, except for one that doesn't exist.

**Comment by ggozad** [comment]
The reason there is no universal error handler is because different platforms throw different errors. Of course it is entirely possible to write a handler that takes care of them all. This is a good candidate for a PR, so please make one and I will review.

**Comment by jvjvjv** [comment]
That's a great idea. I won't be able to as I am a front-end developer and can only handle the iOS portion, so I will spec out a concept for a universal error callback response. I'd need help with performing the updates for the other supported platforms.

I'll leave this open in the meantime.

**Comment by demetris-manikas** [comment]
@ggozad Reading the code shows that an Error object should be returned on all platforms. Can you please verify that a string is returned on iOS when getting a non existent key and report back? Thanks.

**Comment by ggozad** [comment]
@demetris-manikas will look into this asap.

**Comment by ggozad** [comment]
@demetris-manikas errors are returned fine on all platforms, I also included your PR to make sure this is the case. However the issue here is that the error descriptions are not canonical. I.e. different strings come from different platforms. 
I am not sure we should be handling this as we need to look into all possible exceptions thrown and handle them uniformly. This might become a burden as these can change across vendor os releases.

**Comment by jvjvjv** [comment]
1. One option is to leave it up to the end developer to research all possible exceptions across platforms and OS releases, and let them branch their code to handle Android/Windows/iOS exceptions separately. While devs inevitably have to do this, it seems to go against the core value of Cordova development of coding once to work on multiple platforms. (if that's the case you can close this ticket.)
2. Another option is to at least document all of the exceptions each platform/version could return, which is one step better than the above option.
3. The third and most time consuming option would be what I had originally requested.

While I never have any free time I would still like to offer my help. So, if you decide to run with option 2 or 3 let me know. I can definitely work with iOS errors, but not so much Android, and less so Windows.

**Comment by demetris-manikas** [comment]
By just changing 'get' to not call the error callback but the success callback with a null value when a key is not present would solve the problem. But this is an API change  and I am not certain that users would like something like that. The other way to go is to make sure that all platforms return the same error message when calling 'get' with a non existing key.

**Comment by jvjvjv** [comment]
I don't think an API change should be done unless absolutely necessary, and I think this issue can be solved just by making the platforms return the same error, which is actually [what I had originally requested](https://github.com/Crypho/cordova-plugin-secure-storage/issues/91#issue-208195027).

I also mentioned that I'd like to help out with this. I can only work on the iOS portion and my time outside of work is limited (I already do this stuff for my day job), but I could also see how to build an error set that would work for all three platforms. Does that sound good?

**Comment by ggozad** [comment]
@jvjvjv please make a PR handling only the key not found error and returning the same string ("Key not found") for all platforms.
