### ISSUE TITLE
Getting error while installing this

### ISSUE THREAD

**Issue by jouzunasuko** [Crypho/cordova-plugin-secure-storage#92]
`-- cordova-plugin-secure-storage@2.6.3

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by ggozad** [comment]
We haven't seen this ever before. Are you certain your node_modules are not foobared?
Can you check on a new app?

**Comment by demetris-manikas** [comment]
@jouzunasuko Any news on this?

**Comment by jouzunasuko** [comment]
@demetris-manikas not yet T_T
