### ISSUE TITLE
Persistence between apps?

### ISSUE THREAD

**Issue by ehorodyski** [Crypho/cordova-plugin-secure-storage#93]
I work for an organization that develops a suite of apps. We're looking to do SSO between our apps and I was just wondering if the iOS Keychain and Android Keystore are sandboxed or not. It's made very clear that it isn't for Windows, but wanted to confirm on the other platforms.

**Comment by ggozad** [comment]
This is certainly possible on iOS and only has to do with how you configure the keychain access.
Not sure about android, you would need to investigate.
