### ISSUE TITLE
Android: Running 'set' on secure storage error

### ISSUE THREAD

**Issue by jvjvjv** [Crypho/cordova-plugin-secure-storage#94]
In an app where I'm using this, I was trying to immediately set something after it didn't exist. Looks similar to the following:

```javascript
var storage = new cordova.plugins.SecureStorage(_successOnCreateCB, _failOnCreateCB, 'securebioinfo');
storage.get(_successOnGetCB, _failOnGetCB, 'bioIDauth');
```

Now, `_failOnGetCB()` would look like this:

```javascript
var _failOnGetCB = function(error) {
  storage.set(_successOnSetCB, _failOnSetCB, 'bioIDauth', '9abc2ea9-9120a8-cd01c01-c8f18a-etc');
}
```

If run like this at startup, the _failOnSetCB gets an error that reads "chain == null".

If you want me to look further into this, you'd have to wait a while, as my time is severely limited. I wouldn't be able to solve the issue. The only things I can offer are two possible areas to check:

- Directly at app startup, or 
- Directly after a failed get

**Comment by ggozad** [comment]
You need to do whatever operations you want to do after the init success has been called.

**Comment by jvjvjv** [comment]
n00b mistake
