### ISSUE TITLE
iOS - stored keys persist when application is deleted and installed again.

### ISSUE THREAD

**Issue by lukezbikowski** [Crypho/cordova-plugin-secure-storage#97]
I have found the following behaviour I believe is unexpected:
1. install the app and set some keys
2. delete the app
3. install the app again
keys are still there. Is that expected behaviour ? I believe that secured storage should be deleted with an app.

**Comment by ggozad** [comment]
It's a bit unfortunate, but afaik this is the keychain behaviour. I would be happy to merge a PR if you come up with an elegant way to avoid that but not sure it's possible.
For our own app we offer to unlink the user from the app which deletes all keys they might have as a counter-measure.

**Comment by ggozad** [comment]
This is perhaps an OK way of dealing with it if you wanna do a PR on it:
http://stackoverflow.com/questions/4747404/delete-keychain-items-when-an-app-is-uninstalled

**Comment by lukezbikowski** [comment]
Thanks a lot! I will have a look on the aove and let you know gow it goes :-)

btw. Great work with the plugin!  👍

**Comment by shinta5150** [comment]
Has this been added into the plug-in. I'd like to have this behaviour when uninstalling the app on ios
